/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VariableDataOneOf5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VariableDataOneOf5{}

// VariableDataOneOf5 struct for VariableDataOneOf5
type VariableDataOneOf5 struct {
	Property string `json:"property"`
}

type _VariableDataOneOf5 VariableDataOneOf5

// NewVariableDataOneOf5 instantiates a new VariableDataOneOf5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVariableDataOneOf5(property string) *VariableDataOneOf5 {
	this := VariableDataOneOf5{}
	this.Property = property
	return &this
}

// NewVariableDataOneOf5WithDefaults instantiates a new VariableDataOneOf5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVariableDataOneOf5WithDefaults() *VariableDataOneOf5 {
	this := VariableDataOneOf5{}
	return &this
}

// GetProperty returns the Property field value
func (o *VariableDataOneOf5) GetProperty() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Property
}

// GetPropertyOk returns a tuple with the Property field value
// and a boolean to check if the value has been set.
func (o *VariableDataOneOf5) GetPropertyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Property, true
}

// SetProperty sets field value
func (o *VariableDataOneOf5) SetProperty(v string) {
	o.Property = v
}

func (o VariableDataOneOf5) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VariableDataOneOf5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["property"] = o.Property
	return toSerialize, nil
}

func (o *VariableDataOneOf5) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"property",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVariableDataOneOf5 := _VariableDataOneOf5{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVariableDataOneOf5)

	if err != nil {
		return err
	}

	*o = VariableDataOneOf5(varVariableDataOneOf5)

	return err
}

type NullableVariableDataOneOf5 struct {
	value *VariableDataOneOf5
	isSet bool
}

func (v NullableVariableDataOneOf5) Get() *VariableDataOneOf5 {
	return v.value
}

func (v *NullableVariableDataOneOf5) Set(val *VariableDataOneOf5) {
	v.value = val
	v.isSet = true
}

func (v NullableVariableDataOneOf5) IsSet() bool {
	return v.isSet
}

func (v *NullableVariableDataOneOf5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVariableDataOneOf5(val *VariableDataOneOf5) *NullableVariableDataOneOf5 {
	return &NullableVariableDataOneOf5{value: val, isSet: true}
}

func (v NullableVariableDataOneOf5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVariableDataOneOf5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


