/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContributionChangelogBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContributionChangelogBody{}

// ContributionChangelogBody struct for ContributionChangelogBody
type ContributionChangelogBody struct {
	Data Contribution `json:"data"`
	Membership ContributionMembership `json:"membership"`
	Node string `json:"node"`
	PooledContributionId string `json:"pooledContributionId"`
	State int32 `json:"state"`
}

type _ContributionChangelogBody ContributionChangelogBody

// NewContributionChangelogBody instantiates a new ContributionChangelogBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContributionChangelogBody(data Contribution, membership ContributionMembership, node string, pooledContributionId string, state int32) *ContributionChangelogBody {
	this := ContributionChangelogBody{}
	this.Data = data
	this.Membership = membership
	this.Node = node
	this.PooledContributionId = pooledContributionId
	this.State = state
	return &this
}

// NewContributionChangelogBodyWithDefaults instantiates a new ContributionChangelogBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContributionChangelogBodyWithDefaults() *ContributionChangelogBody {
	this := ContributionChangelogBody{}
	return &this
}

// GetData returns the Data field value
func (o *ContributionChangelogBody) GetData() Contribution {
	if o == nil {
		var ret Contribution
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ContributionChangelogBody) GetDataOk() (*Contribution, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ContributionChangelogBody) SetData(v Contribution) {
	o.Data = v
}

// GetMembership returns the Membership field value
func (o *ContributionChangelogBody) GetMembership() ContributionMembership {
	if o == nil {
		var ret ContributionMembership
		return ret
	}

	return o.Membership
}

// GetMembershipOk returns a tuple with the Membership field value
// and a boolean to check if the value has been set.
func (o *ContributionChangelogBody) GetMembershipOk() (*ContributionMembership, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Membership, true
}

// SetMembership sets field value
func (o *ContributionChangelogBody) SetMembership(v ContributionMembership) {
	o.Membership = v
}

// GetNode returns the Node field value
func (o *ContributionChangelogBody) GetNode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Node
}

// GetNodeOk returns a tuple with the Node field value
// and a boolean to check if the value has been set.
func (o *ContributionChangelogBody) GetNodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Node, true
}

// SetNode sets field value
func (o *ContributionChangelogBody) SetNode(v string) {
	o.Node = v
}

// GetPooledContributionId returns the PooledContributionId field value
func (o *ContributionChangelogBody) GetPooledContributionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PooledContributionId
}

// GetPooledContributionIdOk returns a tuple with the PooledContributionId field value
// and a boolean to check if the value has been set.
func (o *ContributionChangelogBody) GetPooledContributionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PooledContributionId, true
}

// SetPooledContributionId sets field value
func (o *ContributionChangelogBody) SetPooledContributionId(v string) {
	o.PooledContributionId = v
}

// GetState returns the State field value
func (o *ContributionChangelogBody) GetState() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ContributionChangelogBody) GetStateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ContributionChangelogBody) SetState(v int32) {
	o.State = v
}

func (o ContributionChangelogBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContributionChangelogBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["membership"] = o.Membership
	toSerialize["node"] = o.Node
	toSerialize["pooledContributionId"] = o.PooledContributionId
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *ContributionChangelogBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"membership",
		"node",
		"pooledContributionId",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContributionChangelogBody := _ContributionChangelogBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContributionChangelogBody)

	if err != nil {
		return err
	}

	*o = ContributionChangelogBody(varContributionChangelogBody)

	return err
}

type NullableContributionChangelogBody struct {
	value *ContributionChangelogBody
	isSet bool
}

func (v NullableContributionChangelogBody) Get() *ContributionChangelogBody {
	return v.value
}

func (v *NullableContributionChangelogBody) Set(val *ContributionChangelogBody) {
	v.value = val
	v.isSet = true
}

func (v NullableContributionChangelogBody) IsSet() bool {
	return v.isSet
}

func (v *NullableContributionChangelogBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContributionChangelogBody(val *ContributionChangelogBody) *NullableContributionChangelogBody {
	return &NullableContributionChangelogBody{value: val, isSet: true}
}

func (v NullableContributionChangelogBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContributionChangelogBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


