/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DataShapesOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataShapesOneOf3{}

// DataShapesOneOf3 struct for DataShapesOneOf3
type DataShapesOneOf3 struct {
	ListTwoD CalcListTwoD `json:"listTwoD"`
}

type _DataShapesOneOf3 DataShapesOneOf3

// NewDataShapesOneOf3 instantiates a new DataShapesOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataShapesOneOf3(listTwoD CalcListTwoD) *DataShapesOneOf3 {
	this := DataShapesOneOf3{}
	this.ListTwoD = listTwoD
	return &this
}

// NewDataShapesOneOf3WithDefaults instantiates a new DataShapesOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataShapesOneOf3WithDefaults() *DataShapesOneOf3 {
	this := DataShapesOneOf3{}
	return &this
}

// GetListTwoD returns the ListTwoD field value
func (o *DataShapesOneOf3) GetListTwoD() CalcListTwoD {
	if o == nil {
		var ret CalcListTwoD
		return ret
	}

	return o.ListTwoD
}

// GetListTwoDOk returns a tuple with the ListTwoD field value
// and a boolean to check if the value has been set.
func (o *DataShapesOneOf3) GetListTwoDOk() (*CalcListTwoD, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ListTwoD, true
}

// SetListTwoD sets field value
func (o *DataShapesOneOf3) SetListTwoD(v CalcListTwoD) {
	o.ListTwoD = v
}

func (o DataShapesOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataShapesOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["listTwoD"] = o.ListTwoD
	return toSerialize, nil
}

func (o *DataShapesOneOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"listTwoD",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataShapesOneOf3 := _DataShapesOneOf3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataShapesOneOf3)

	if err != nil {
		return err
	}

	*o = DataShapesOneOf3(varDataShapesOneOf3)

	return err
}

type NullableDataShapesOneOf3 struct {
	value *DataShapesOneOf3
	isSet bool
}

func (v NullableDataShapesOneOf3) Get() *DataShapesOneOf3 {
	return v.value
}

func (v *NullableDataShapesOneOf3) Set(val *DataShapesOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableDataShapesOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableDataShapesOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataShapesOneOf3(val *DataShapesOneOf3) *NullableDataShapesOneOf3 {
	return &NullableDataShapesOneOf3{value: val, isSet: true}
}

func (v NullableDataShapesOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataShapesOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


