/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PropertyBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PropertyBody{}

// PropertyBody struct for PropertyBody
type PropertyBody struct {
	Delete bool `json:"delete"`
	DeleteAllNodes bool `json:"deleteAllNodes"`
	Description *string `json:"description,omitempty"`
	IsPublic *bool `json:"isPublic,omitempty"`
	Name *string `json:"name,omitempty"`
	Node []PropertyNodeUpdate `json:"node"`
	Type *int32 `json:"type,omitempty"`
}

type _PropertyBody PropertyBody

// NewPropertyBody instantiates a new PropertyBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPropertyBody(delete bool, deleteAllNodes bool, node []PropertyNodeUpdate) *PropertyBody {
	this := PropertyBody{}
	this.Delete = delete
	this.DeleteAllNodes = deleteAllNodes
	this.Node = node
	return &this
}

// NewPropertyBodyWithDefaults instantiates a new PropertyBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPropertyBodyWithDefaults() *PropertyBody {
	this := PropertyBody{}
	return &this
}

// GetDelete returns the Delete field value
func (o *PropertyBody) GetDelete() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value
// and a boolean to check if the value has been set.
func (o *PropertyBody) GetDeleteOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delete, true
}

// SetDelete sets field value
func (o *PropertyBody) SetDelete(v bool) {
	o.Delete = v
}

// GetDeleteAllNodes returns the DeleteAllNodes field value
func (o *PropertyBody) GetDeleteAllNodes() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DeleteAllNodes
}

// GetDeleteAllNodesOk returns a tuple with the DeleteAllNodes field value
// and a boolean to check if the value has been set.
func (o *PropertyBody) GetDeleteAllNodesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeleteAllNodes, true
}

// SetDeleteAllNodes sets field value
func (o *PropertyBody) SetDeleteAllNodes(v bool) {
	o.DeleteAllNodes = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PropertyBody) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertyBody) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PropertyBody) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PropertyBody) SetDescription(v string) {
	o.Description = &v
}

// GetIsPublic returns the IsPublic field value if set, zero value otherwise.
func (o *PropertyBody) GetIsPublic() bool {
	if o == nil || IsNil(o.IsPublic) {
		var ret bool
		return ret
	}
	return *o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertyBody) GetIsPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublic) {
		return nil, false
	}
	return o.IsPublic, true
}

// HasIsPublic returns a boolean if a field has been set.
func (o *PropertyBody) HasIsPublic() bool {
	if o != nil && !IsNil(o.IsPublic) {
		return true
	}

	return false
}

// SetIsPublic gets a reference to the given bool and assigns it to the IsPublic field.
func (o *PropertyBody) SetIsPublic(v bool) {
	o.IsPublic = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PropertyBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertyBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PropertyBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PropertyBody) SetName(v string) {
	o.Name = &v
}

// GetNode returns the Node field value
func (o *PropertyBody) GetNode() []PropertyNodeUpdate {
	if o == nil {
		var ret []PropertyNodeUpdate
		return ret
	}

	return o.Node
}

// GetNodeOk returns a tuple with the Node field value
// and a boolean to check if the value has been set.
func (o *PropertyBody) GetNodeOk() ([]PropertyNodeUpdate, bool) {
	if o == nil {
		return nil, false
	}
	return o.Node, true
}

// SetNode sets field value
func (o *PropertyBody) SetNode(v []PropertyNodeUpdate) {
	o.Node = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PropertyBody) GetType() int32 {
	if o == nil || IsNil(o.Type) {
		var ret int32
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PropertyBody) GetTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PropertyBody) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given int32 and assigns it to the Type field.
func (o *PropertyBody) SetType(v int32) {
	o.Type = &v
}

func (o PropertyBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PropertyBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["delete"] = o.Delete
	toSerialize["deleteAllNodes"] = o.DeleteAllNodes
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IsPublic) {
		toSerialize["isPublic"] = o.IsPublic
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["node"] = o.Node
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *PropertyBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"delete",
		"deleteAllNodes",
		"node",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPropertyBody := _PropertyBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPropertyBody)

	if err != nil {
		return err
	}

	*o = PropertyBody(varPropertyBody)

	return err
}

type NullablePropertyBody struct {
	value *PropertyBody
	isSet bool
}

func (v NullablePropertyBody) Get() *PropertyBody {
	return v.value
}

func (v *NullablePropertyBody) Set(val *PropertyBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePropertyBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePropertyBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePropertyBody(val *PropertyBody) *NullablePropertyBody {
	return &NullablePropertyBody{value: val, isSet: true}
}

func (v NullablePropertyBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePropertyBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


