/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PropertyNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PropertyNode{}

// PropertyNode struct for PropertyNode
type PropertyNode struct {
	Children []PropertyNode `json:"children"`
	HexCode string `json:"hexCode"`
	Id string `json:"id"`
	Name string `json:"name"`
	Position int32 `json:"position"`
}

type _PropertyNode PropertyNode

// NewPropertyNode instantiates a new PropertyNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPropertyNode(children []PropertyNode, hexCode string, id string, name string, position int32) *PropertyNode {
	this := PropertyNode{}
	this.Children = children
	this.HexCode = hexCode
	this.Id = id
	this.Name = name
	this.Position = position
	return &this
}

// NewPropertyNodeWithDefaults instantiates a new PropertyNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPropertyNodeWithDefaults() *PropertyNode {
	this := PropertyNode{}
	return &this
}

// GetChildren returns the Children field value
func (o *PropertyNode) GetChildren() []PropertyNode {
	if o == nil {
		var ret []PropertyNode
		return ret
	}

	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value
// and a boolean to check if the value has been set.
func (o *PropertyNode) GetChildrenOk() ([]PropertyNode, bool) {
	if o == nil {
		return nil, false
	}
	return o.Children, true
}

// SetChildren sets field value
func (o *PropertyNode) SetChildren(v []PropertyNode) {
	o.Children = v
}

// GetHexCode returns the HexCode field value
func (o *PropertyNode) GetHexCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HexCode
}

// GetHexCodeOk returns a tuple with the HexCode field value
// and a boolean to check if the value has been set.
func (o *PropertyNode) GetHexCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HexCode, true
}

// SetHexCode sets field value
func (o *PropertyNode) SetHexCode(v string) {
	o.HexCode = v
}

// GetId returns the Id field value
func (o *PropertyNode) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PropertyNode) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PropertyNode) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *PropertyNode) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PropertyNode) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PropertyNode) SetName(v string) {
	o.Name = v
}

// GetPosition returns the Position field value
func (o *PropertyNode) GetPosition() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *PropertyNode) GetPositionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *PropertyNode) SetPosition(v int32) {
	o.Position = v
}

func (o PropertyNode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PropertyNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["children"] = o.Children
	toSerialize["hexCode"] = o.HexCode
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["position"] = o.Position
	return toSerialize, nil
}

func (o *PropertyNode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"children",
		"hexCode",
		"id",
		"name",
		"position",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPropertyNode := _PropertyNode{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPropertyNode)

	if err != nil {
		return err
	}

	*o = PropertyNode(varPropertyNode)

	return err
}

type NullablePropertyNode struct {
	value *PropertyNode
	isSet bool
}

func (v NullablePropertyNode) Get() *PropertyNode {
	return v.value
}

func (v *NullablePropertyNode) Set(val *PropertyNode) {
	v.value = val
	v.isSet = true
}

func (v NullablePropertyNode) IsSet() bool {
	return v.isSet
}

func (v *NullablePropertyNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePropertyNode(val *PropertyNode) *NullablePropertyNode {
	return &NullablePropertyNode{value: val, isSet: true}
}

func (v NullablePropertyNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePropertyNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


