/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
)

// checks if the FloorplanPatchParamsBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FloorplanPatchParamsBody{}

// FloorplanPatchParamsBody struct for FloorplanPatchParamsBody
type FloorplanPatchParamsBody struct {
	CreatedAt *int64 `json:"createdAt,omitempty"`
	Name *string `json:"name,omitempty"`
	OverlayOffset *FloorplanChangelogOverlayOffset `json:"overlayOffset,omitempty"`
	Property *string `json:"property,omitempty"`
	PropertyNode *string `json:"propertyNode,omitempty"`
	Spaces *FloorplanCreateSpaceRepeated `json:"spaces,omitempty"`
}

// NewFloorplanPatchParamsBody instantiates a new FloorplanPatchParamsBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFloorplanPatchParamsBody() *FloorplanPatchParamsBody {
	this := FloorplanPatchParamsBody{}
	return &this
}

// NewFloorplanPatchParamsBodyWithDefaults instantiates a new FloorplanPatchParamsBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFloorplanPatchParamsBodyWithDefaults() *FloorplanPatchParamsBody {
	this := FloorplanPatchParamsBody{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FloorplanPatchParamsBody) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FloorplanPatchParamsBody) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FloorplanPatchParamsBody) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *FloorplanPatchParamsBody) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FloorplanPatchParamsBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FloorplanPatchParamsBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FloorplanPatchParamsBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FloorplanPatchParamsBody) SetName(v string) {
	o.Name = &v
}

// GetOverlayOffset returns the OverlayOffset field value if set, zero value otherwise.
func (o *FloorplanPatchParamsBody) GetOverlayOffset() FloorplanChangelogOverlayOffset {
	if o == nil || IsNil(o.OverlayOffset) {
		var ret FloorplanChangelogOverlayOffset
		return ret
	}
	return *o.OverlayOffset
}

// GetOverlayOffsetOk returns a tuple with the OverlayOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FloorplanPatchParamsBody) GetOverlayOffsetOk() (*FloorplanChangelogOverlayOffset, bool) {
	if o == nil || IsNil(o.OverlayOffset) {
		return nil, false
	}
	return o.OverlayOffset, true
}

// HasOverlayOffset returns a boolean if a field has been set.
func (o *FloorplanPatchParamsBody) HasOverlayOffset() bool {
	if o != nil && !IsNil(o.OverlayOffset) {
		return true
	}

	return false
}

// SetOverlayOffset gets a reference to the given FloorplanChangelogOverlayOffset and assigns it to the OverlayOffset field.
func (o *FloorplanPatchParamsBody) SetOverlayOffset(v FloorplanChangelogOverlayOffset) {
	o.OverlayOffset = &v
}

// GetProperty returns the Property field value if set, zero value otherwise.
func (o *FloorplanPatchParamsBody) GetProperty() string {
	if o == nil || IsNil(o.Property) {
		var ret string
		return ret
	}
	return *o.Property
}

// GetPropertyOk returns a tuple with the Property field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FloorplanPatchParamsBody) GetPropertyOk() (*string, bool) {
	if o == nil || IsNil(o.Property) {
		return nil, false
	}
	return o.Property, true
}

// HasProperty returns a boolean if a field has been set.
func (o *FloorplanPatchParamsBody) HasProperty() bool {
	if o != nil && !IsNil(o.Property) {
		return true
	}

	return false
}

// SetProperty gets a reference to the given string and assigns it to the Property field.
func (o *FloorplanPatchParamsBody) SetProperty(v string) {
	o.Property = &v
}

// GetPropertyNode returns the PropertyNode field value if set, zero value otherwise.
func (o *FloorplanPatchParamsBody) GetPropertyNode() string {
	if o == nil || IsNil(o.PropertyNode) {
		var ret string
		return ret
	}
	return *o.PropertyNode
}

// GetPropertyNodeOk returns a tuple with the PropertyNode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FloorplanPatchParamsBody) GetPropertyNodeOk() (*string, bool) {
	if o == nil || IsNil(o.PropertyNode) {
		return nil, false
	}
	return o.PropertyNode, true
}

// HasPropertyNode returns a boolean if a field has been set.
func (o *FloorplanPatchParamsBody) HasPropertyNode() bool {
	if o != nil && !IsNil(o.PropertyNode) {
		return true
	}

	return false
}

// SetPropertyNode gets a reference to the given string and assigns it to the PropertyNode field.
func (o *FloorplanPatchParamsBody) SetPropertyNode(v string) {
	o.PropertyNode = &v
}

// GetSpaces returns the Spaces field value if set, zero value otherwise.
func (o *FloorplanPatchParamsBody) GetSpaces() FloorplanCreateSpaceRepeated {
	if o == nil || IsNil(o.Spaces) {
		var ret FloorplanCreateSpaceRepeated
		return ret
	}
	return *o.Spaces
}

// GetSpacesOk returns a tuple with the Spaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FloorplanPatchParamsBody) GetSpacesOk() (*FloorplanCreateSpaceRepeated, bool) {
	if o == nil || IsNil(o.Spaces) {
		return nil, false
	}
	return o.Spaces, true
}

// HasSpaces returns a boolean if a field has been set.
func (o *FloorplanPatchParamsBody) HasSpaces() bool {
	if o != nil && !IsNil(o.Spaces) {
		return true
	}

	return false
}

// SetSpaces gets a reference to the given FloorplanCreateSpaceRepeated and assigns it to the Spaces field.
func (o *FloorplanPatchParamsBody) SetSpaces(v FloorplanCreateSpaceRepeated) {
	o.Spaces = &v
}

func (o FloorplanPatchParamsBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FloorplanPatchParamsBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OverlayOffset) {
		toSerialize["overlayOffset"] = o.OverlayOffset
	}
	if !IsNil(o.Property) {
		toSerialize["property"] = o.Property
	}
	if !IsNil(o.PropertyNode) {
		toSerialize["propertyNode"] = o.PropertyNode
	}
	if !IsNil(o.Spaces) {
		toSerialize["spaces"] = o.Spaces
	}
	return toSerialize, nil
}

type NullableFloorplanPatchParamsBody struct {
	value *FloorplanPatchParamsBody
	isSet bool
}

func (v NullableFloorplanPatchParamsBody) Get() *FloorplanPatchParamsBody {
	return v.value
}

func (v *NullableFloorplanPatchParamsBody) Set(val *FloorplanPatchParamsBody) {
	v.value = val
	v.isSet = true
}

func (v NullableFloorplanPatchParamsBody) IsSet() bool {
	return v.isSet
}

func (v *NullableFloorplanPatchParamsBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFloorplanPatchParamsBody(val *FloorplanPatchParamsBody) *NullableFloorplanPatchParamsBody {
	return &NullableFloorplanPatchParamsBody{value: val, isSet: true}
}

func (v NullableFloorplanPatchParamsBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFloorplanPatchParamsBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


