/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Cookie type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Cookie{}

// Cookie struct for Cookie
type Cookie struct {
	Domain string `json:"Domain"`
	Expires time.Time `json:"Expires"`
	HttpOnly bool `json:"HttpOnly"`
	MaxAge int64 `json:"MaxAge"`
	Name string `json:"Name"`
	Partitioned bool `json:"Partitioned"`
	Path string `json:"Path"`
	Quoted bool `json:"Quoted"`
	Raw string `json:"Raw"`
	RawExpires string `json:"RawExpires"`
	SameSite int64 `json:"SameSite"`
	Secure bool `json:"Secure"`
	Unparsed []string `json:"Unparsed"`
	Value string `json:"Value"`
}

type _Cookie Cookie

// NewCookie instantiates a new Cookie object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCookie(domain string, expires time.Time, httpOnly bool, maxAge int64, name string, partitioned bool, path string, quoted bool, raw string, rawExpires string, sameSite int64, secure bool, unparsed []string, value string) *Cookie {
	this := Cookie{}
	this.Domain = domain
	this.Expires = expires
	this.HttpOnly = httpOnly
	this.MaxAge = maxAge
	this.Name = name
	this.Partitioned = partitioned
	this.Path = path
	this.Quoted = quoted
	this.Raw = raw
	this.RawExpires = rawExpires
	this.SameSite = sameSite
	this.Secure = secure
	this.Unparsed = unparsed
	this.Value = value
	return &this
}

// NewCookieWithDefaults instantiates a new Cookie object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCookieWithDefaults() *Cookie {
	this := Cookie{}
	return &this
}

// GetDomain returns the Domain field value
func (o *Cookie) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *Cookie) SetDomain(v string) {
	o.Domain = v
}

// GetExpires returns the Expires field value
func (o *Cookie) GetExpires() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetExpiresOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expires, true
}

// SetExpires sets field value
func (o *Cookie) SetExpires(v time.Time) {
	o.Expires = v
}

// GetHttpOnly returns the HttpOnly field value
func (o *Cookie) GetHttpOnly() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HttpOnly
}

// GetHttpOnlyOk returns a tuple with the HttpOnly field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetHttpOnlyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HttpOnly, true
}

// SetHttpOnly sets field value
func (o *Cookie) SetHttpOnly(v bool) {
	o.HttpOnly = v
}

// GetMaxAge returns the MaxAge field value
func (o *Cookie) GetMaxAge() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MaxAge
}

// GetMaxAgeOk returns a tuple with the MaxAge field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetMaxAgeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxAge, true
}

// SetMaxAge sets field value
func (o *Cookie) SetMaxAge(v int64) {
	o.MaxAge = v
}

// GetName returns the Name field value
func (o *Cookie) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Cookie) SetName(v string) {
	o.Name = v
}

// GetPartitioned returns the Partitioned field value
func (o *Cookie) GetPartitioned() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Partitioned
}

// GetPartitionedOk returns a tuple with the Partitioned field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetPartitionedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Partitioned, true
}

// SetPartitioned sets field value
func (o *Cookie) SetPartitioned(v bool) {
	o.Partitioned = v
}

// GetPath returns the Path field value
func (o *Cookie) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *Cookie) SetPath(v string) {
	o.Path = v
}

// GetQuoted returns the Quoted field value
func (o *Cookie) GetQuoted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Quoted
}

// GetQuotedOk returns a tuple with the Quoted field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetQuotedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quoted, true
}

// SetQuoted sets field value
func (o *Cookie) SetQuoted(v bool) {
	o.Quoted = v
}

// GetRaw returns the Raw field value
func (o *Cookie) GetRaw() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Raw
}

// GetRawOk returns a tuple with the Raw field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetRawOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Raw, true
}

// SetRaw sets field value
func (o *Cookie) SetRaw(v string) {
	o.Raw = v
}

// GetRawExpires returns the RawExpires field value
func (o *Cookie) GetRawExpires() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RawExpires
}

// GetRawExpiresOk returns a tuple with the RawExpires field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetRawExpiresOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RawExpires, true
}

// SetRawExpires sets field value
func (o *Cookie) SetRawExpires(v string) {
	o.RawExpires = v
}

// GetSameSite returns the SameSite field value
func (o *Cookie) GetSameSite() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SameSite
}

// GetSameSiteOk returns a tuple with the SameSite field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetSameSiteOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SameSite, true
}

// SetSameSite sets field value
func (o *Cookie) SetSameSite(v int64) {
	o.SameSite = v
}

// GetSecure returns the Secure field value
func (o *Cookie) GetSecure() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Secure
}

// GetSecureOk returns a tuple with the Secure field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetSecureOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secure, true
}

// SetSecure sets field value
func (o *Cookie) SetSecure(v bool) {
	o.Secure = v
}

// GetUnparsed returns the Unparsed field value
func (o *Cookie) GetUnparsed() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Unparsed
}

// GetUnparsedOk returns a tuple with the Unparsed field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetUnparsedOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Unparsed, true
}

// SetUnparsed sets field value
func (o *Cookie) SetUnparsed(v []string) {
	o.Unparsed = v
}

// GetValue returns the Value field value
func (o *Cookie) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Cookie) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Cookie) SetValue(v string) {
	o.Value = v
}

func (o Cookie) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Cookie) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Domain"] = o.Domain
	toSerialize["Expires"] = o.Expires
	toSerialize["HttpOnly"] = o.HttpOnly
	toSerialize["MaxAge"] = o.MaxAge
	toSerialize["Name"] = o.Name
	toSerialize["Partitioned"] = o.Partitioned
	toSerialize["Path"] = o.Path
	toSerialize["Quoted"] = o.Quoted
	toSerialize["Raw"] = o.Raw
	toSerialize["RawExpires"] = o.RawExpires
	toSerialize["SameSite"] = o.SameSite
	toSerialize["Secure"] = o.Secure
	toSerialize["Unparsed"] = o.Unparsed
	toSerialize["Value"] = o.Value
	return toSerialize, nil
}

func (o *Cookie) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Domain",
		"Expires",
		"HttpOnly",
		"MaxAge",
		"Name",
		"Partitioned",
		"Path",
		"Quoted",
		"Raw",
		"RawExpires",
		"SameSite",
		"Secure",
		"Unparsed",
		"Value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCookie := _Cookie{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCookie)

	if err != nil {
		return err
	}

	*o = Cookie(varCookie)

	return err
}

type NullableCookie struct {
	value *Cookie
	isSet bool
}

func (v NullableCookie) Get() *Cookie {
	return v.value
}

func (v *NullableCookie) Set(val *Cookie) {
	v.value = val
	v.isSet = true
}

func (v NullableCookie) IsSet() bool {
	return v.isSet
}

func (v *NullableCookie) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCookie(val *Cookie) *NullableCookie {
	return &NullableCookie{value: val, isSet: true}
}

func (v NullableCookie) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCookie) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


