/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
)

// checks if the VariablePatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VariablePatch{}

// VariablePatch struct for VariablePatch
type VariablePatch struct {
	Data *VariableData `json:"data,omitempty"`
	Delete *bool `json:"delete,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewVariablePatch instantiates a new VariablePatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVariablePatch() *VariablePatch {
	this := VariablePatch{}
	return &this
}

// NewVariablePatchWithDefaults instantiates a new VariablePatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVariablePatchWithDefaults() *VariablePatch {
	this := VariablePatch{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *VariablePatch) GetData() VariableData {
	if o == nil || IsNil(o.Data) {
		var ret VariableData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariablePatch) GetDataOk() (*VariableData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *VariablePatch) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given VariableData and assigns it to the Data field.
func (o *VariablePatch) SetData(v VariableData) {
	o.Data = &v
}

// GetDelete returns the Delete field value if set, zero value otherwise.
func (o *VariablePatch) GetDelete() bool {
	if o == nil || IsNil(o.Delete) {
		var ret bool
		return ret
	}
	return *o.Delete
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariablePatch) GetDeleteOk() (*bool, bool) {
	if o == nil || IsNil(o.Delete) {
		return nil, false
	}
	return o.Delete, true
}

// HasDelete returns a boolean if a field has been set.
func (o *VariablePatch) HasDelete() bool {
	if o != nil && !IsNil(o.Delete) {
		return true
	}

	return false
}

// SetDelete gets a reference to the given bool and assigns it to the Delete field.
func (o *VariablePatch) SetDelete(v bool) {
	o.Delete = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *VariablePatch) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VariablePatch) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *VariablePatch) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *VariablePatch) SetName(v string) {
	o.Name = &v
}

func (o VariablePatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VariablePatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Delete) {
		toSerialize["delete"] = o.Delete
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableVariablePatch struct {
	value *VariablePatch
	isSet bool
}

func (v NullableVariablePatch) Get() *VariablePatch {
	return v.value
}

func (v *NullableVariablePatch) Set(val *VariablePatch) {
	v.value = val
	v.isSet = true
}

func (v NullableVariablePatch) IsSet() bool {
	return v.isSet
}

func (v *NullableVariablePatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVariablePatch(val *VariablePatch) *NullableVariablePatch {
	return &NullableVariablePatch{value: val, isSet: true}
}

func (v NullableVariablePatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVariablePatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


