/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthLoginPublicReqBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthLoginPublicReqBody{}

// AuthLoginPublicReqBody struct for AuthLoginPublicReqBody
type AuthLoginPublicReqBody struct {
	AcceptTerms bool `json:"acceptTerms"`
	Hostname string `json:"hostname"`
}

type _AuthLoginPublicReqBody AuthLoginPublicReqBody

// NewAuthLoginPublicReqBody instantiates a new AuthLoginPublicReqBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthLoginPublicReqBody(acceptTerms bool, hostname string) *AuthLoginPublicReqBody {
	this := AuthLoginPublicReqBody{}
	this.AcceptTerms = acceptTerms
	this.Hostname = hostname
	return &this
}

// NewAuthLoginPublicReqBodyWithDefaults instantiates a new AuthLoginPublicReqBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthLoginPublicReqBodyWithDefaults() *AuthLoginPublicReqBody {
	this := AuthLoginPublicReqBody{}
	return &this
}

// GetAcceptTerms returns the AcceptTerms field value
func (o *AuthLoginPublicReqBody) GetAcceptTerms() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AcceptTerms
}

// GetAcceptTermsOk returns a tuple with the AcceptTerms field value
// and a boolean to check if the value has been set.
func (o *AuthLoginPublicReqBody) GetAcceptTermsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AcceptTerms, true
}

// SetAcceptTerms sets field value
func (o *AuthLoginPublicReqBody) SetAcceptTerms(v bool) {
	o.AcceptTerms = v
}

// GetHostname returns the Hostname field value
func (o *AuthLoginPublicReqBody) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *AuthLoginPublicReqBody) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *AuthLoginPublicReqBody) SetHostname(v string) {
	o.Hostname = v
}

func (o AuthLoginPublicReqBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthLoginPublicReqBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["acceptTerms"] = o.AcceptTerms
	toSerialize["hostname"] = o.Hostname
	return toSerialize, nil
}

func (o *AuthLoginPublicReqBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"acceptTerms",
		"hostname",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthLoginPublicReqBody := _AuthLoginPublicReqBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthLoginPublicReqBody)

	if err != nil {
		return err
	}

	*o = AuthLoginPublicReqBody(varAuthLoginPublicReqBody)

	return err
}

type NullableAuthLoginPublicReqBody struct {
	value *AuthLoginPublicReqBody
	isSet bool
}

func (v NullableAuthLoginPublicReqBody) Get() *AuthLoginPublicReqBody {
	return v.value
}

func (v *NullableAuthLoginPublicReqBody) Set(val *AuthLoginPublicReqBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthLoginPublicReqBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthLoginPublicReqBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthLoginPublicReqBody(val *AuthLoginPublicReqBody) *NullableAuthLoginPublicReqBody {
	return &NullableAuthLoginPublicReqBody{value: val, isSet: true}
}

func (v NullableAuthLoginPublicReqBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthLoginPublicReqBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


