/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EntryPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntryPatch{}

// EntryPatch struct for EntryPatch
type EntryPatch struct {
	// The id of an entry that already exists in the object group.
	Id string `json:"id"`
	// Renames the entry.
	Name *string `json:"name,omitempty"`
	// The properties to merge into the entry, keyed by property id. Properties the request does not name are left as they are.
	Properties map[string]EntryPatchPropertiesValue `json:"properties,omitempty"`
	// Replaces the entry's user.
	User *string `json:"user,omitempty"`
}

type _EntryPatch EntryPatch

// NewEntryPatch instantiates a new EntryPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntryPatch(id string) *EntryPatch {
	this := EntryPatch{}
	this.Id = id
	return &this
}

// NewEntryPatchWithDefaults instantiates a new EntryPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntryPatchWithDefaults() *EntryPatch {
	this := EntryPatch{}
	return &this
}

// GetId returns the Id field value
func (o *EntryPatch) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EntryPatch) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EntryPatch) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EntryPatch) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntryPatch) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EntryPatch) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EntryPatch) SetName(v string) {
	o.Name = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *EntryPatch) GetProperties() map[string]EntryPatchPropertiesValue {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]EntryPatchPropertiesValue
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntryPatch) GetPropertiesOk() (map[string]EntryPatchPropertiesValue, bool) {
	if o == nil || IsNil(o.Properties) {
		return map[string]EntryPatchPropertiesValue{}, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *EntryPatch) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]EntryPatchPropertiesValue and assigns it to the Properties field.
func (o *EntryPatch) SetProperties(v map[string]EntryPatchPropertiesValue) {
	o.Properties = v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *EntryPatch) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntryPatch) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *EntryPatch) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *EntryPatch) SetUser(v string) {
	o.User = &v
}

func (o EntryPatch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntryPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

func (o *EntryPatch) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntryPatch := _EntryPatch{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntryPatch)

	if err != nil {
		return err
	}

	*o = EntryPatch(varEntryPatch)

	return err
}

type NullableEntryPatch struct {
	value *EntryPatch
	isSet bool
}

func (v NullableEntryPatch) Get() *EntryPatch {
	return v.value
}

func (v *NullableEntryPatch) Set(val *EntryPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableEntryPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableEntryPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntryPatch(val *EntryPatch) *NullableEntryPatch {
	return &NullableEntryPatch{value: val, isSet: true}
}

func (v NullableEntryPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntryPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


