/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
)

// checks if the UserV2PatchReqBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserV2PatchReqBody{}

// UserV2PatchReqBody struct for UserV2PatchReqBody
type UserV2PatchReqBody struct {
	AcceptMarketing *bool `json:"acceptMarketing,omitempty"`
	EmployeeID *string `json:"employeeID,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName *string `json:"lastName,omitempty"`
	// BCP 47 locale code to set for the authenticated user. Pass an empty string to clear the preference.
	LocaleCode *string `json:"localeCode,omitempty"`
	// Role name to assign to the target user. Omit (with roleUser or roleUserEmail present) to revoke the user's current role.
	Role *string `json:"role,omitempty"`
	// ID of the user whose role should be updated. Requires the *Manage users* permission.
	RoleUser *int64 `json:"roleUser,omitempty"`
	// Email of the user whose role should be updated. If no account exists for this address, an invitation is sent. Requires the *Manage users* permission.
	RoleUserEmail *string `json:"roleUserEmail,omitempty"`
	// Arbitrary key-value pairs persisted for client UI state. Merged with any existing entries.
	Store map[string]string `json:"store,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewUserV2PatchReqBody instantiates a new UserV2PatchReqBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserV2PatchReqBody() *UserV2PatchReqBody {
	this := UserV2PatchReqBody{}
	return &this
}

// NewUserV2PatchReqBodyWithDefaults instantiates a new UserV2PatchReqBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserV2PatchReqBodyWithDefaults() *UserV2PatchReqBody {
	this := UserV2PatchReqBody{}
	return &this
}

// GetAcceptMarketing returns the AcceptMarketing field value if set, zero value otherwise.
func (o *UserV2PatchReqBody) GetAcceptMarketing() bool {
	if o == nil || IsNil(o.AcceptMarketing) {
		var ret bool
		return ret
	}
	return *o.AcceptMarketing
}

// GetAcceptMarketingOk returns a tuple with the AcceptMarketing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserV2PatchReqBody) GetAcceptMarketingOk() (*bool, bool) {
	if o == nil || IsNil(o.AcceptMarketing) {
		return nil, false
	}
	return o.AcceptMarketing, true
}

// HasAcceptMarketing returns a boolean if a field has been set.
func (o *UserV2PatchReqBody) HasAcceptMarketing() bool {
	if o != nil && !IsNil(o.AcceptMarketing) {
		return true
	}

	return false
}

// SetAcceptMarketing gets a reference to the given bool and assigns it to the AcceptMarketing field.
func (o *UserV2PatchReqBody) SetAcceptMarketing(v bool) {
	o.AcceptMarketing = &v
}

// GetEmployeeID returns the EmployeeID field value if set, zero value otherwise.
func (o *UserV2PatchReqBody) GetEmployeeID() string {
	if o == nil || IsNil(o.EmployeeID) {
		var ret string
		return ret
	}
	return *o.EmployeeID
}

// GetEmployeeIDOk returns a tuple with the EmployeeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserV2PatchReqBody) GetEmployeeIDOk() (*string, bool) {
	if o == nil || IsNil(o.EmployeeID) {
		return nil, false
	}
	return o.EmployeeID, true
}

// HasEmployeeID returns a boolean if a field has been set.
func (o *UserV2PatchReqBody) HasEmployeeID() bool {
	if o != nil && !IsNil(o.EmployeeID) {
		return true
	}

	return false
}

// SetEmployeeID gets a reference to the given string and assigns it to the EmployeeID field.
func (o *UserV2PatchReqBody) SetEmployeeID(v string) {
	o.EmployeeID = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UserV2PatchReqBody) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserV2PatchReqBody) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UserV2PatchReqBody) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UserV2PatchReqBody) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UserV2PatchReqBody) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserV2PatchReqBody) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UserV2PatchReqBody) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UserV2PatchReqBody) SetLastName(v string) {
	o.LastName = &v
}

// GetLocaleCode returns the LocaleCode field value if set, zero value otherwise.
func (o *UserV2PatchReqBody) GetLocaleCode() string {
	if o == nil || IsNil(o.LocaleCode) {
		var ret string
		return ret
	}
	return *o.LocaleCode
}

// GetLocaleCodeOk returns a tuple with the LocaleCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserV2PatchReqBody) GetLocaleCodeOk() (*string, bool) {
	if o == nil || IsNil(o.LocaleCode) {
		return nil, false
	}
	return o.LocaleCode, true
}

// HasLocaleCode returns a boolean if a field has been set.
func (o *UserV2PatchReqBody) HasLocaleCode() bool {
	if o != nil && !IsNil(o.LocaleCode) {
		return true
	}

	return false
}

// SetLocaleCode gets a reference to the given string and assigns it to the LocaleCode field.
func (o *UserV2PatchReqBody) SetLocaleCode(v string) {
	o.LocaleCode = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *UserV2PatchReqBody) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserV2PatchReqBody) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *UserV2PatchReqBody) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *UserV2PatchReqBody) SetRole(v string) {
	o.Role = &v
}

// GetRoleUser returns the RoleUser field value if set, zero value otherwise.
func (o *UserV2PatchReqBody) GetRoleUser() int64 {
	if o == nil || IsNil(o.RoleUser) {
		var ret int64
		return ret
	}
	return *o.RoleUser
}

// GetRoleUserOk returns a tuple with the RoleUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserV2PatchReqBody) GetRoleUserOk() (*int64, bool) {
	if o == nil || IsNil(o.RoleUser) {
		return nil, false
	}
	return o.RoleUser, true
}

// HasRoleUser returns a boolean if a field has been set.
func (o *UserV2PatchReqBody) HasRoleUser() bool {
	if o != nil && !IsNil(o.RoleUser) {
		return true
	}

	return false
}

// SetRoleUser gets a reference to the given int64 and assigns it to the RoleUser field.
func (o *UserV2PatchReqBody) SetRoleUser(v int64) {
	o.RoleUser = &v
}

// GetRoleUserEmail returns the RoleUserEmail field value if set, zero value otherwise.
func (o *UserV2PatchReqBody) GetRoleUserEmail() string {
	if o == nil || IsNil(o.RoleUserEmail) {
		var ret string
		return ret
	}
	return *o.RoleUserEmail
}

// GetRoleUserEmailOk returns a tuple with the RoleUserEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserV2PatchReqBody) GetRoleUserEmailOk() (*string, bool) {
	if o == nil || IsNil(o.RoleUserEmail) {
		return nil, false
	}
	return o.RoleUserEmail, true
}

// HasRoleUserEmail returns a boolean if a field has been set.
func (o *UserV2PatchReqBody) HasRoleUserEmail() bool {
	if o != nil && !IsNil(o.RoleUserEmail) {
		return true
	}

	return false
}

// SetRoleUserEmail gets a reference to the given string and assigns it to the RoleUserEmail field.
func (o *UserV2PatchReqBody) SetRoleUserEmail(v string) {
	o.RoleUserEmail = &v
}

// GetStore returns the Store field value if set, zero value otherwise.
func (o *UserV2PatchReqBody) GetStore() map[string]string {
	if o == nil || IsNil(o.Store) {
		var ret map[string]string
		return ret
	}
	return o.Store
}

// GetStoreOk returns a tuple with the Store field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserV2PatchReqBody) GetStoreOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Store) {
		return map[string]string{}, false
	}
	return o.Store, true
}

// HasStore returns a boolean if a field has been set.
func (o *UserV2PatchReqBody) HasStore() bool {
	if o != nil && !IsNil(o.Store) {
		return true
	}

	return false
}

// SetStore gets a reference to the given map[string]string and assigns it to the Store field.
func (o *UserV2PatchReqBody) SetStore(v map[string]string) {
	o.Store = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *UserV2PatchReqBody) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserV2PatchReqBody) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *UserV2PatchReqBody) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *UserV2PatchReqBody) SetTitle(v string) {
	o.Title = &v
}

func (o UserV2PatchReqBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserV2PatchReqBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AcceptMarketing) {
		toSerialize["acceptMarketing"] = o.AcceptMarketing
	}
	if !IsNil(o.EmployeeID) {
		toSerialize["employeeID"] = o.EmployeeID
	}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.LocaleCode) {
		toSerialize["localeCode"] = o.LocaleCode
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.RoleUser) {
		toSerialize["roleUser"] = o.RoleUser
	}
	if !IsNil(o.RoleUserEmail) {
		toSerialize["roleUserEmail"] = o.RoleUserEmail
	}
	if !IsNil(o.Store) {
		toSerialize["store"] = o.Store
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	return toSerialize, nil
}

type NullableUserV2PatchReqBody struct {
	value *UserV2PatchReqBody
	isSet bool
}

func (v NullableUserV2PatchReqBody) Get() *UserV2PatchReqBody {
	return v.value
}

func (v *NullableUserV2PatchReqBody) Set(val *UserV2PatchReqBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUserV2PatchReqBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUserV2PatchReqBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserV2PatchReqBody(val *UserV2PatchReqBody) *NullableUserV2PatchReqBody {
	return &NullableUserV2PatchReqBody{value: val, isSet: true}
}

func (v NullableUserV2PatchReqBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserV2PatchReqBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


