/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetTopDownModelEntriesRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTopDownModelEntriesRes{}

// GetTopDownModelEntriesRes struct for GetTopDownModelEntriesRes
type GetTopDownModelEntriesRes struct {
	List []TopDownModelEntryList `json:"list"`
	Total int32 `json:"total"`
}

type _GetTopDownModelEntriesRes GetTopDownModelEntriesRes

// NewGetTopDownModelEntriesRes instantiates a new GetTopDownModelEntriesRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTopDownModelEntriesRes(list []TopDownModelEntryList, total int32) *GetTopDownModelEntriesRes {
	this := GetTopDownModelEntriesRes{}
	this.List = list
	this.Total = total
	return &this
}

// NewGetTopDownModelEntriesResWithDefaults instantiates a new GetTopDownModelEntriesRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTopDownModelEntriesResWithDefaults() *GetTopDownModelEntriesRes {
	this := GetTopDownModelEntriesRes{}
	return &this
}

// GetList returns the List field value
func (o *GetTopDownModelEntriesRes) GetList() []TopDownModelEntryList {
	if o == nil {
		var ret []TopDownModelEntryList
		return ret
	}

	return o.List
}

// GetListOk returns a tuple with the List field value
// and a boolean to check if the value has been set.
func (o *GetTopDownModelEntriesRes) GetListOk() ([]TopDownModelEntryList, bool) {
	if o == nil {
		return nil, false
	}
	return o.List, true
}

// SetList sets field value
func (o *GetTopDownModelEntriesRes) SetList(v []TopDownModelEntryList) {
	o.List = v
}

// GetTotal returns the Total field value
func (o *GetTopDownModelEntriesRes) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *GetTopDownModelEntriesRes) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *GetTopDownModelEntriesRes) SetTotal(v int32) {
	o.Total = v
}

func (o GetTopDownModelEntriesRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTopDownModelEntriesRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["list"] = o.List
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *GetTopDownModelEntriesRes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"list",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetTopDownModelEntriesRes := _GetTopDownModelEntriesRes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetTopDownModelEntriesRes)

	if err != nil {
		return err
	}

	*o = GetTopDownModelEntriesRes(varGetTopDownModelEntriesRes)

	return err
}

type NullableGetTopDownModelEntriesRes struct {
	value *GetTopDownModelEntriesRes
	isSet bool
}

func (v NullableGetTopDownModelEntriesRes) Get() *GetTopDownModelEntriesRes {
	return v.value
}

func (v *NullableGetTopDownModelEntriesRes) Set(val *GetTopDownModelEntriesRes) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTopDownModelEntriesRes) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTopDownModelEntriesRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTopDownModelEntriesRes(val *GetTopDownModelEntriesRes) *NullableGetTopDownModelEntriesRes {
	return &NullableGetTopDownModelEntriesRes{value: val, isSet: true}
}

func (v NullableGetTopDownModelEntriesRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTopDownModelEntriesRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


