/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SingleSelectListData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SingleSelectListData{}

// SingleSelectListData struct for SingleSelectListData
type SingleSelectListData struct {
	Categories []ChangelogOption `json:"categories"`
	Options []ChangelogValueOption `json:"options"`
}

type _SingleSelectListData SingleSelectListData

// NewSingleSelectListData instantiates a new SingleSelectListData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSingleSelectListData(categories []ChangelogOption, options []ChangelogValueOption) *SingleSelectListData {
	this := SingleSelectListData{}
	this.Categories = categories
	this.Options = options
	return &this
}

// NewSingleSelectListDataWithDefaults instantiates a new SingleSelectListData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSingleSelectListDataWithDefaults() *SingleSelectListData {
	this := SingleSelectListData{}
	return &this
}

// GetCategories returns the Categories field value
func (o *SingleSelectListData) GetCategories() []ChangelogOption {
	if o == nil {
		var ret []ChangelogOption
		return ret
	}

	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value
// and a boolean to check if the value has been set.
func (o *SingleSelectListData) GetCategoriesOk() ([]ChangelogOption, bool) {
	if o == nil {
		return nil, false
	}
	return o.Categories, true
}

// SetCategories sets field value
func (o *SingleSelectListData) SetCategories(v []ChangelogOption) {
	o.Categories = v
}

// GetOptions returns the Options field value
func (o *SingleSelectListData) GetOptions() []ChangelogValueOption {
	if o == nil {
		var ret []ChangelogValueOption
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *SingleSelectListData) GetOptionsOk() ([]ChangelogValueOption, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options, true
}

// SetOptions sets field value
func (o *SingleSelectListData) SetOptions(v []ChangelogValueOption) {
	o.Options = v
}

func (o SingleSelectListData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SingleSelectListData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["categories"] = o.Categories
	toSerialize["options"] = o.Options
	return toSerialize, nil
}

func (o *SingleSelectListData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"categories",
		"options",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSingleSelectListData := _SingleSelectListData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSingleSelectListData)

	if err != nil {
		return err
	}

	*o = SingleSelectListData(varSingleSelectListData)

	return err
}

type NullableSingleSelectListData struct {
	value *SingleSelectListData
	isSet bool
}

func (v NullableSingleSelectListData) Get() *SingleSelectListData {
	return v.value
}

func (v *NullableSingleSelectListData) Set(val *SingleSelectListData) {
	v.value = val
	v.isSet = true
}

func (v NullableSingleSelectListData) IsSet() bool {
	return v.isSet
}

func (v *NullableSingleSelectListData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSingleSelectListData(val *SingleSelectListData) *NullableSingleSelectListData {
	return &NullableSingleSelectListData{value: val, isSet: true}
}

func (v NullableSingleSelectListData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSingleSelectListData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


