/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CalcRuleRefOneOf4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalcRuleRefOneOf4{}

// CalcRuleRefOneOf4 struct for CalcRuleRefOneOf4
type CalcRuleRefOneOf4 struct {
	SumOf CalcRuleRef `json:"sumOf"`
}

type _CalcRuleRefOneOf4 CalcRuleRefOneOf4

// NewCalcRuleRefOneOf4 instantiates a new CalcRuleRefOneOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalcRuleRefOneOf4(sumOf CalcRuleRef) *CalcRuleRefOneOf4 {
	this := CalcRuleRefOneOf4{}
	this.SumOf = sumOf
	return &this
}

// NewCalcRuleRefOneOf4WithDefaults instantiates a new CalcRuleRefOneOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalcRuleRefOneOf4WithDefaults() *CalcRuleRefOneOf4 {
	this := CalcRuleRefOneOf4{}
	return &this
}

// GetSumOf returns the SumOf field value
func (o *CalcRuleRefOneOf4) GetSumOf() CalcRuleRef {
	if o == nil {
		var ret CalcRuleRef
		return ret
	}

	return o.SumOf
}

// GetSumOfOk returns a tuple with the SumOf field value
// and a boolean to check if the value has been set.
func (o *CalcRuleRefOneOf4) GetSumOfOk() (*CalcRuleRef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SumOf, true
}

// SetSumOf sets field value
func (o *CalcRuleRefOneOf4) SetSumOf(v CalcRuleRef) {
	o.SumOf = v
}

func (o CalcRuleRefOneOf4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalcRuleRefOneOf4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sumOf"] = o.SumOf
	return toSerialize, nil
}

func (o *CalcRuleRefOneOf4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sumOf",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCalcRuleRefOneOf4 := _CalcRuleRefOneOf4{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCalcRuleRefOneOf4)

	if err != nil {
		return err
	}

	*o = CalcRuleRefOneOf4(varCalcRuleRefOneOf4)

	return err
}

type NullableCalcRuleRefOneOf4 struct {
	value *CalcRuleRefOneOf4
	isSet bool
}

func (v NullableCalcRuleRefOneOf4) Get() *CalcRuleRefOneOf4 {
	return v.value
}

func (v *NullableCalcRuleRefOneOf4) Set(val *CalcRuleRefOneOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableCalcRuleRefOneOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableCalcRuleRefOneOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalcRuleRefOneOf4(val *CalcRuleRefOneOf4) *NullableCalcRuleRefOneOf4 {
	return &NullableCalcRuleRefOneOf4{value: val, isSet: true}
}

func (v NullableCalcRuleRefOneOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalcRuleRefOneOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


