/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Orphan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Orphan{}

// Orphan struct for Orphan
type Orphan struct {
	Account int64 `json:"account"`
	Action string `json:"action"`
	FileId string `json:"fileId"`
	LastModified time.Time `json:"lastModified"`
	Size int64 `json:"size"`
}

type _Orphan Orphan

// NewOrphan instantiates a new Orphan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrphan(account int64, action string, fileId string, lastModified time.Time, size int64) *Orphan {
	this := Orphan{}
	this.Account = account
	this.Action = action
	this.FileId = fileId
	this.LastModified = lastModified
	this.Size = size
	return &this
}

// NewOrphanWithDefaults instantiates a new Orphan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrphanWithDefaults() *Orphan {
	this := Orphan{}
	return &this
}

// GetAccount returns the Account field value
func (o *Orphan) GetAccount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *Orphan) GetAccountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *Orphan) SetAccount(v int64) {
	o.Account = v
}

// GetAction returns the Action field value
func (o *Orphan) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *Orphan) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *Orphan) SetAction(v string) {
	o.Action = v
}

// GetFileId returns the FileId field value
func (o *Orphan) GetFileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value
// and a boolean to check if the value has been set.
func (o *Orphan) GetFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileId, true
}

// SetFileId sets field value
func (o *Orphan) SetFileId(v string) {
	o.FileId = v
}

// GetLastModified returns the LastModified field value
func (o *Orphan) GetLastModified() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value
// and a boolean to check if the value has been set.
func (o *Orphan) GetLastModifiedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastModified, true
}

// SetLastModified sets field value
func (o *Orphan) SetLastModified(v time.Time) {
	o.LastModified = v
}

// GetSize returns the Size field value
func (o *Orphan) GetSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *Orphan) GetSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *Orphan) SetSize(v int64) {
	o.Size = v
}

func (o Orphan) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Orphan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account"] = o.Account
	toSerialize["action"] = o.Action
	toSerialize["fileId"] = o.FileId
	toSerialize["lastModified"] = o.LastModified
	toSerialize["size"] = o.Size
	return toSerialize, nil
}

func (o *Orphan) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account",
		"action",
		"fileId",
		"lastModified",
		"size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrphan := _Orphan{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrphan)

	if err != nil {
		return err
	}

	*o = Orphan(varOrphan)

	return err
}

type NullableOrphan struct {
	value *Orphan
	isSet bool
}

func (v NullableOrphan) Get() *Orphan {
	return v.value
}

func (v *NullableOrphan) Set(val *Orphan) {
	v.value = val
	v.isSet = true
}

func (v NullableOrphan) IsSet() bool {
	return v.isSet
}

func (v *NullableOrphan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrphan(val *Orphan) *NullableOrphan {
	return &NullableOrphan{value: val, isSet: true}
}

func (v NullableOrphan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrphan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


