/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectListEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectListEntry{}

// ProjectListEntry struct for ProjectListEntry
type ProjectListEntry struct {
	Description string `json:"description"`
	Filter []FilterGroup `json:"filter"`
	Id float64 `json:"id"`
	Name string `json:"name"`
	Status string `json:"status"`
	Variables map[string]VariableChangelog `json:"variables"`
}

type _ProjectListEntry ProjectListEntry

// NewProjectListEntry instantiates a new ProjectListEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectListEntry(description string, filter []FilterGroup, id float64, name string, status string, variables map[string]VariableChangelog) *ProjectListEntry {
	this := ProjectListEntry{}
	this.Description = description
	this.Filter = filter
	this.Id = id
	this.Name = name
	this.Status = status
	this.Variables = variables
	return &this
}

// NewProjectListEntryWithDefaults instantiates a new ProjectListEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectListEntryWithDefaults() *ProjectListEntry {
	this := ProjectListEntry{}
	return &this
}

// GetDescription returns the Description field value
func (o *ProjectListEntry) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ProjectListEntry) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ProjectListEntry) SetDescription(v string) {
	o.Description = v
}

// GetFilter returns the Filter field value
func (o *ProjectListEntry) GetFilter() []FilterGroup {
	if o == nil {
		var ret []FilterGroup
		return ret
	}

	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value
// and a boolean to check if the value has been set.
func (o *ProjectListEntry) GetFilterOk() ([]FilterGroup, bool) {
	if o == nil {
		return nil, false
	}
	return o.Filter, true
}

// SetFilter sets field value
func (o *ProjectListEntry) SetFilter(v []FilterGroup) {
	o.Filter = v
}

// GetId returns the Id field value
func (o *ProjectListEntry) GetId() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProjectListEntry) GetIdOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProjectListEntry) SetId(v float64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ProjectListEntry) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProjectListEntry) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProjectListEntry) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *ProjectListEntry) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ProjectListEntry) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ProjectListEntry) SetStatus(v string) {
	o.Status = v
}

// GetVariables returns the Variables field value
func (o *ProjectListEntry) GetVariables() map[string]VariableChangelog {
	if o == nil {
		var ret map[string]VariableChangelog
		return ret
	}

	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value
// and a boolean to check if the value has been set.
func (o *ProjectListEntry) GetVariablesOk() (map[string]VariableChangelog, bool) {
	if o == nil {
		return map[string]VariableChangelog{}, false
	}
	return o.Variables, true
}

// SetVariables sets field value
func (o *ProjectListEntry) SetVariables(v map[string]VariableChangelog) {
	o.Variables = v
}

func (o ProjectListEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectListEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["filter"] = o.Filter
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	toSerialize["variables"] = o.Variables
	return toSerialize, nil
}

func (o *ProjectListEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"filter",
		"id",
		"name",
		"status",
		"variables",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectListEntry := _ProjectListEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectListEntry)

	if err != nil {
		return err
	}

	*o = ProjectListEntry(varProjectListEntry)

	return err
}

type NullableProjectListEntry struct {
	value *ProjectListEntry
	isSet bool
}

func (v NullableProjectListEntry) Get() *ProjectListEntry {
	return v.value
}

func (v *NullableProjectListEntry) Set(val *ProjectListEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectListEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectListEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectListEntry(val *ProjectListEntry) *NullableProjectListEntry {
	return &NullableProjectListEntry{value: val, isSet: true}
}

func (v NullableProjectListEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectListEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


