/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContributionListEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContributionListEntry{}

// ContributionListEntry struct for ContributionListEntry
type ContributionListEntry struct {
	ContributionChangelogBody ContributionChangelogBody `json:"contributionChangelogBody"`
	Email string `json:"email"`
	FirstName string `json:"firstName"`
	Userid string `json:"userid"`
}

type _ContributionListEntry ContributionListEntry

// NewContributionListEntry instantiates a new ContributionListEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContributionListEntry(contributionChangelogBody ContributionChangelogBody, email string, firstName string, userid string) *ContributionListEntry {
	this := ContributionListEntry{}
	this.ContributionChangelogBody = contributionChangelogBody
	this.Email = email
	this.FirstName = firstName
	this.Userid = userid
	return &this
}

// NewContributionListEntryWithDefaults instantiates a new ContributionListEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContributionListEntryWithDefaults() *ContributionListEntry {
	this := ContributionListEntry{}
	return &this
}

// GetContributionChangelogBody returns the ContributionChangelogBody field value
func (o *ContributionListEntry) GetContributionChangelogBody() ContributionChangelogBody {
	if o == nil {
		var ret ContributionChangelogBody
		return ret
	}

	return o.ContributionChangelogBody
}

// GetContributionChangelogBodyOk returns a tuple with the ContributionChangelogBody field value
// and a boolean to check if the value has been set.
func (o *ContributionListEntry) GetContributionChangelogBodyOk() (*ContributionChangelogBody, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContributionChangelogBody, true
}

// SetContributionChangelogBody sets field value
func (o *ContributionListEntry) SetContributionChangelogBody(v ContributionChangelogBody) {
	o.ContributionChangelogBody = v
}

// GetEmail returns the Email field value
func (o *ContributionListEntry) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ContributionListEntry) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ContributionListEntry) SetEmail(v string) {
	o.Email = v
}

// GetFirstName returns the FirstName field value
func (o *ContributionListEntry) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *ContributionListEntry) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *ContributionListEntry) SetFirstName(v string) {
	o.FirstName = v
}

// GetUserid returns the Userid field value
func (o *ContributionListEntry) GetUserid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Userid
}

// GetUseridOk returns a tuple with the Userid field value
// and a boolean to check if the value has been set.
func (o *ContributionListEntry) GetUseridOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Userid, true
}

// SetUserid sets field value
func (o *ContributionListEntry) SetUserid(v string) {
	o.Userid = v
}

func (o ContributionListEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContributionListEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contributionChangelogBody"] = o.ContributionChangelogBody
	toSerialize["email"] = o.Email
	toSerialize["firstName"] = o.FirstName
	toSerialize["userid"] = o.Userid
	return toSerialize, nil
}

func (o *ContributionListEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"contributionChangelogBody",
		"email",
		"firstName",
		"userid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContributionListEntry := _ContributionListEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContributionListEntry)

	if err != nil {
		return err
	}

	*o = ContributionListEntry(varContributionListEntry)

	return err
}

type NullableContributionListEntry struct {
	value *ContributionListEntry
	isSet bool
}

func (v NullableContributionListEntry) Get() *ContributionListEntry {
	return v.value
}

func (v *NullableContributionListEntry) Set(val *ContributionListEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableContributionListEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableContributionListEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContributionListEntry(val *ContributionListEntry) *NullableContributionListEntry {
	return &NullableContributionListEntry{value: val, isSet: true}
}

func (v NullableContributionListEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContributionListEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


