/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ScenarioListRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScenarioListRes{}

// ScenarioListRes struct for ScenarioListRes
type ScenarioListRes struct {
	Scenarios []ScenarioListEntry `json:"scenarios"`
}

type _ScenarioListRes ScenarioListRes

// NewScenarioListRes instantiates a new ScenarioListRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScenarioListRes(scenarios []ScenarioListEntry) *ScenarioListRes {
	this := ScenarioListRes{}
	this.Scenarios = scenarios
	return &this
}

// NewScenarioListResWithDefaults instantiates a new ScenarioListRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScenarioListResWithDefaults() *ScenarioListRes {
	this := ScenarioListRes{}
	return &this
}

// GetScenarios returns the Scenarios field value
func (o *ScenarioListRes) GetScenarios() []ScenarioListEntry {
	if o == nil {
		var ret []ScenarioListEntry
		return ret
	}

	return o.Scenarios
}

// GetScenariosOk returns a tuple with the Scenarios field value
// and a boolean to check if the value has been set.
func (o *ScenarioListRes) GetScenariosOk() ([]ScenarioListEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scenarios, true
}

// SetScenarios sets field value
func (o *ScenarioListRes) SetScenarios(v []ScenarioListEntry) {
	o.Scenarios = v
}

func (o ScenarioListRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScenarioListRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scenarios"] = o.Scenarios
	return toSerialize, nil
}

func (o *ScenarioListRes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scenarios",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScenarioListRes := _ScenarioListRes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScenarioListRes)

	if err != nil {
		return err
	}

	*o = ScenarioListRes(varScenarioListRes)

	return err
}

type NullableScenarioListRes struct {
	value *ScenarioListRes
	isSet bool
}

func (v NullableScenarioListRes) Get() *ScenarioListRes {
	return v.value
}

func (v *NullableScenarioListRes) Set(val *ScenarioListRes) {
	v.value = val
	v.isSet = true
}

func (v NullableScenarioListRes) IsSet() bool {
	return v.isSet
}

func (v *NullableScenarioListRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScenarioListRes(val *ScenarioListRes) *NullableScenarioListRes {
	return &NullableScenarioListRes{value: val, isSet: true}
}

func (v NullableScenarioListRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScenarioListRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


