/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InOfficeHoursData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InOfficeHoursData{}

// InOfficeHoursData struct for InOfficeHoursData
type InOfficeHoursData struct {
	Friday InOfficeData `json:"friday"`
	Monday InOfficeData `json:"monday"`
	Saturday InOfficeData `json:"saturday"`
	Sunday InOfficeData `json:"sunday"`
	Thursday InOfficeData `json:"thursday"`
	Tuesday InOfficeData `json:"tuesday"`
	Wednesday InOfficeData `json:"wednesday"`
}

type _InOfficeHoursData InOfficeHoursData

// NewInOfficeHoursData instantiates a new InOfficeHoursData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInOfficeHoursData(friday InOfficeData, monday InOfficeData, saturday InOfficeData, sunday InOfficeData, thursday InOfficeData, tuesday InOfficeData, wednesday InOfficeData) *InOfficeHoursData {
	this := InOfficeHoursData{}
	this.Friday = friday
	this.Monday = monday
	this.Saturday = saturday
	this.Sunday = sunday
	this.Thursday = thursday
	this.Tuesday = tuesday
	this.Wednesday = wednesday
	return &this
}

// NewInOfficeHoursDataWithDefaults instantiates a new InOfficeHoursData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInOfficeHoursDataWithDefaults() *InOfficeHoursData {
	this := InOfficeHoursData{}
	return &this
}

// GetFriday returns the Friday field value
func (o *InOfficeHoursData) GetFriday() InOfficeData {
	if o == nil {
		var ret InOfficeData
		return ret
	}

	return o.Friday
}

// GetFridayOk returns a tuple with the Friday field value
// and a boolean to check if the value has been set.
func (o *InOfficeHoursData) GetFridayOk() (*InOfficeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Friday, true
}

// SetFriday sets field value
func (o *InOfficeHoursData) SetFriday(v InOfficeData) {
	o.Friday = v
}

// GetMonday returns the Monday field value
func (o *InOfficeHoursData) GetMonday() InOfficeData {
	if o == nil {
		var ret InOfficeData
		return ret
	}

	return o.Monday
}

// GetMondayOk returns a tuple with the Monday field value
// and a boolean to check if the value has been set.
func (o *InOfficeHoursData) GetMondayOk() (*InOfficeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Monday, true
}

// SetMonday sets field value
func (o *InOfficeHoursData) SetMonday(v InOfficeData) {
	o.Monday = v
}

// GetSaturday returns the Saturday field value
func (o *InOfficeHoursData) GetSaturday() InOfficeData {
	if o == nil {
		var ret InOfficeData
		return ret
	}

	return o.Saturday
}

// GetSaturdayOk returns a tuple with the Saturday field value
// and a boolean to check if the value has been set.
func (o *InOfficeHoursData) GetSaturdayOk() (*InOfficeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Saturday, true
}

// SetSaturday sets field value
func (o *InOfficeHoursData) SetSaturday(v InOfficeData) {
	o.Saturday = v
}

// GetSunday returns the Sunday field value
func (o *InOfficeHoursData) GetSunday() InOfficeData {
	if o == nil {
		var ret InOfficeData
		return ret
	}

	return o.Sunday
}

// GetSundayOk returns a tuple with the Sunday field value
// and a boolean to check if the value has been set.
func (o *InOfficeHoursData) GetSundayOk() (*InOfficeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sunday, true
}

// SetSunday sets field value
func (o *InOfficeHoursData) SetSunday(v InOfficeData) {
	o.Sunday = v
}

// GetThursday returns the Thursday field value
func (o *InOfficeHoursData) GetThursday() InOfficeData {
	if o == nil {
		var ret InOfficeData
		return ret
	}

	return o.Thursday
}

// GetThursdayOk returns a tuple with the Thursday field value
// and a boolean to check if the value has been set.
func (o *InOfficeHoursData) GetThursdayOk() (*InOfficeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Thursday, true
}

// SetThursday sets field value
func (o *InOfficeHoursData) SetThursday(v InOfficeData) {
	o.Thursday = v
}

// GetTuesday returns the Tuesday field value
func (o *InOfficeHoursData) GetTuesday() InOfficeData {
	if o == nil {
		var ret InOfficeData
		return ret
	}

	return o.Tuesday
}

// GetTuesdayOk returns a tuple with the Tuesday field value
// and a boolean to check if the value has been set.
func (o *InOfficeHoursData) GetTuesdayOk() (*InOfficeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tuesday, true
}

// SetTuesday sets field value
func (o *InOfficeHoursData) SetTuesday(v InOfficeData) {
	o.Tuesday = v
}

// GetWednesday returns the Wednesday field value
func (o *InOfficeHoursData) GetWednesday() InOfficeData {
	if o == nil {
		var ret InOfficeData
		return ret
	}

	return o.Wednesday
}

// GetWednesdayOk returns a tuple with the Wednesday field value
// and a boolean to check if the value has been set.
func (o *InOfficeHoursData) GetWednesdayOk() (*InOfficeData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Wednesday, true
}

// SetWednesday sets field value
func (o *InOfficeHoursData) SetWednesday(v InOfficeData) {
	o.Wednesday = v
}

func (o InOfficeHoursData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InOfficeHoursData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["friday"] = o.Friday
	toSerialize["monday"] = o.Monday
	toSerialize["saturday"] = o.Saturday
	toSerialize["sunday"] = o.Sunday
	toSerialize["thursday"] = o.Thursday
	toSerialize["tuesday"] = o.Tuesday
	toSerialize["wednesday"] = o.Wednesday
	return toSerialize, nil
}

func (o *InOfficeHoursData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"friday",
		"monday",
		"saturday",
		"sunday",
		"thursday",
		"tuesday",
		"wednesday",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInOfficeHoursData := _InOfficeHoursData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInOfficeHoursData)

	if err != nil {
		return err
	}

	*o = InOfficeHoursData(varInOfficeHoursData)

	return err
}

type NullableInOfficeHoursData struct {
	value *InOfficeHoursData
	isSet bool
}

func (v NullableInOfficeHoursData) Get() *InOfficeHoursData {
	return v.value
}

func (v *NullableInOfficeHoursData) Set(val *InOfficeHoursData) {
	v.value = val
	v.isSet = true
}

func (v NullableInOfficeHoursData) IsSet() bool {
	return v.isSet
}

func (v *NullableInOfficeHoursData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInOfficeHoursData(val *InOfficeHoursData) *NullableInOfficeHoursData {
	return &NullableInOfficeHoursData{value: val, isSet: true}
}

func (v NullableInOfficeHoursData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInOfficeHoursData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


