/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VariableChangelog type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VariableChangelog{}

// VariableChangelog struct for VariableChangelog
type VariableChangelog struct {
	Data VariableData `json:"data"`
	Name string `json:"name"`
}

type _VariableChangelog VariableChangelog

// NewVariableChangelog instantiates a new VariableChangelog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVariableChangelog(data VariableData, name string) *VariableChangelog {
	this := VariableChangelog{}
	this.Data = data
	this.Name = name
	return &this
}

// NewVariableChangelogWithDefaults instantiates a new VariableChangelog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVariableChangelogWithDefaults() *VariableChangelog {
	this := VariableChangelog{}
	return &this
}

// GetData returns the Data field value
func (o *VariableChangelog) GetData() VariableData {
	if o == nil {
		var ret VariableData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VariableChangelog) GetDataOk() (*VariableData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *VariableChangelog) SetData(v VariableData) {
	o.Data = v
}

// GetName returns the Name field value
func (o *VariableChangelog) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VariableChangelog) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VariableChangelog) SetName(v string) {
	o.Name = v
}

func (o VariableChangelog) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VariableChangelog) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *VariableChangelog) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVariableChangelog := _VariableChangelog{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVariableChangelog)

	if err != nil {
		return err
	}

	*o = VariableChangelog(varVariableChangelog)

	return err
}

type NullableVariableChangelog struct {
	value *VariableChangelog
	isSet bool
}

func (v NullableVariableChangelog) Get() *VariableChangelog {
	return v.value
}

func (v *NullableVariableChangelog) Set(val *VariableChangelog) {
	v.value = val
	v.isSet = true
}

func (v NullableVariableChangelog) IsSet() bool {
	return v.isSet
}

func (v *NullableVariableChangelog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVariableChangelog(val *VariableChangelog) *NullableVariableChangelog {
	return &NullableVariableChangelog{value: val, isSet: true}
}

func (v NullableVariableChangelog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVariableChangelog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


