/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LayerOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LayerOneOf3{}

// LayerOneOf3 struct for LayerOneOf3
type LayerOneOf3 struct {
	Rule map[string]interface{} `json:"rule"`
}

type _LayerOneOf3 LayerOneOf3

// NewLayerOneOf3 instantiates a new LayerOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLayerOneOf3(rule map[string]interface{}) *LayerOneOf3 {
	this := LayerOneOf3{}
	this.Rule = rule
	return &this
}

// NewLayerOneOf3WithDefaults instantiates a new LayerOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLayerOneOf3WithDefaults() *LayerOneOf3 {
	this := LayerOneOf3{}
	return &this
}

// GetRule returns the Rule field value
func (o *LayerOneOf3) GetRule() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Rule
}

// GetRuleOk returns a tuple with the Rule field value
// and a boolean to check if the value has been set.
func (o *LayerOneOf3) GetRuleOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Rule, true
}

// SetRule sets field value
func (o *LayerOneOf3) SetRule(v map[string]interface{}) {
	o.Rule = v
}

func (o LayerOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LayerOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["rule"] = o.Rule
	return toSerialize, nil
}

func (o *LayerOneOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rule",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLayerOneOf3 := _LayerOneOf3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLayerOneOf3)

	if err != nil {
		return err
	}

	*o = LayerOneOf3(varLayerOneOf3)

	return err
}

type NullableLayerOneOf3 struct {
	value *LayerOneOf3
	isSet bool
}

func (v NullableLayerOneOf3) Get() *LayerOneOf3 {
	return v.value
}

func (v *NullableLayerOneOf3) Set(val *LayerOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableLayerOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableLayerOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLayerOneOf3(val *LayerOneOf3) *NullableLayerOneOf3 {
	return &NullableLayerOneOf3{value: val, isSet: true}
}

func (v NullableLayerOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLayerOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


