/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AccountCalculationUsageDay type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountCalculationUsageDay{}

// AccountCalculationUsageDay struct for AccountCalculationUsageDay
type AccountCalculationUsageDay struct {
	// Credits used aggregating: one per 10,000 objects read by a sum.
	Aggregation int64 `json:"aggregation"`
	// Credits used by the AI assistant.
	Ai int64 `json:"ai"`
	// Credits used building layer data: one per 1,000 objects written.
	Build int64 `json:"build"`
	// UTC day the usage was recorded on.
	Date string `json:"date"`
}

type _AccountCalculationUsageDay AccountCalculationUsageDay

// NewAccountCalculationUsageDay instantiates a new AccountCalculationUsageDay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountCalculationUsageDay(aggregation int64, ai int64, build int64, date string) *AccountCalculationUsageDay {
	this := AccountCalculationUsageDay{}
	this.Aggregation = aggregation
	this.Ai = ai
	this.Build = build
	this.Date = date
	return &this
}

// NewAccountCalculationUsageDayWithDefaults instantiates a new AccountCalculationUsageDay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountCalculationUsageDayWithDefaults() *AccountCalculationUsageDay {
	this := AccountCalculationUsageDay{}
	return &this
}

// GetAggregation returns the Aggregation field value
func (o *AccountCalculationUsageDay) GetAggregation() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Aggregation
}

// GetAggregationOk returns a tuple with the Aggregation field value
// and a boolean to check if the value has been set.
func (o *AccountCalculationUsageDay) GetAggregationOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aggregation, true
}

// SetAggregation sets field value
func (o *AccountCalculationUsageDay) SetAggregation(v int64) {
	o.Aggregation = v
}

// GetAi returns the Ai field value
func (o *AccountCalculationUsageDay) GetAi() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Ai
}

// GetAiOk returns a tuple with the Ai field value
// and a boolean to check if the value has been set.
func (o *AccountCalculationUsageDay) GetAiOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ai, true
}

// SetAi sets field value
func (o *AccountCalculationUsageDay) SetAi(v int64) {
	o.Ai = v
}

// GetBuild returns the Build field value
func (o *AccountCalculationUsageDay) GetBuild() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Build
}

// GetBuildOk returns a tuple with the Build field value
// and a boolean to check if the value has been set.
func (o *AccountCalculationUsageDay) GetBuildOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Build, true
}

// SetBuild sets field value
func (o *AccountCalculationUsageDay) SetBuild(v int64) {
	o.Build = v
}

// GetDate returns the Date field value
func (o *AccountCalculationUsageDay) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *AccountCalculationUsageDay) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *AccountCalculationUsageDay) SetDate(v string) {
	o.Date = v
}

func (o AccountCalculationUsageDay) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountCalculationUsageDay) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["aggregation"] = o.Aggregation
	toSerialize["ai"] = o.Ai
	toSerialize["build"] = o.Build
	toSerialize["date"] = o.Date
	return toSerialize, nil
}

func (o *AccountCalculationUsageDay) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"aggregation",
		"ai",
		"build",
		"date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountCalculationUsageDay := _AccountCalculationUsageDay{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountCalculationUsageDay)

	if err != nil {
		return err
	}

	*o = AccountCalculationUsageDay(varAccountCalculationUsageDay)

	return err
}

type NullableAccountCalculationUsageDay struct {
	value *AccountCalculationUsageDay
	isSet bool
}

func (v NullableAccountCalculationUsageDay) Get() *AccountCalculationUsageDay {
	return v.value
}

func (v *NullableAccountCalculationUsageDay) Set(val *AccountCalculationUsageDay) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountCalculationUsageDay) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountCalculationUsageDay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountCalculationUsageDay(val *AccountCalculationUsageDay) *NullableAccountCalculationUsageDay {
	return &NullableAccountCalculationUsageDay{value: val, isSet: true}
}

func (v NullableAccountCalculationUsageDay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountCalculationUsageDay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


