/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FloorplanGetBodySpace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FloorplanGetBodySpace{}

// FloorplanGetBodySpace struct for FloorplanGetBodySpace
type FloorplanGetBodySpace struct {
	Location string `json:"location"`
	Paths [][]FloorplanGetBodySpacePoint `json:"paths"`
}

type _FloorplanGetBodySpace FloorplanGetBodySpace

// NewFloorplanGetBodySpace instantiates a new FloorplanGetBodySpace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFloorplanGetBodySpace(location string, paths [][]FloorplanGetBodySpacePoint) *FloorplanGetBodySpace {
	this := FloorplanGetBodySpace{}
	this.Location = location
	this.Paths = paths
	return &this
}

// NewFloorplanGetBodySpaceWithDefaults instantiates a new FloorplanGetBodySpace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFloorplanGetBodySpaceWithDefaults() *FloorplanGetBodySpace {
	this := FloorplanGetBodySpace{}
	return &this
}

// GetLocation returns the Location field value
func (o *FloorplanGetBodySpace) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *FloorplanGetBodySpace) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *FloorplanGetBodySpace) SetLocation(v string) {
	o.Location = v
}

// GetPaths returns the Paths field value
func (o *FloorplanGetBodySpace) GetPaths() [][]FloorplanGetBodySpacePoint {
	if o == nil {
		var ret [][]FloorplanGetBodySpacePoint
		return ret
	}

	return o.Paths
}

// GetPathsOk returns a tuple with the Paths field value
// and a boolean to check if the value has been set.
func (o *FloorplanGetBodySpace) GetPathsOk() ([][]FloorplanGetBodySpacePoint, bool) {
	if o == nil {
		return nil, false
	}
	return o.Paths, true
}

// SetPaths sets field value
func (o *FloorplanGetBodySpace) SetPaths(v [][]FloorplanGetBodySpacePoint) {
	o.Paths = v
}

func (o FloorplanGetBodySpace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FloorplanGetBodySpace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["location"] = o.Location
	toSerialize["paths"] = o.Paths
	return toSerialize, nil
}

func (o *FloorplanGetBodySpace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"location",
		"paths",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFloorplanGetBodySpace := _FloorplanGetBodySpace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFloorplanGetBodySpace)

	if err != nil {
		return err
	}

	*o = FloorplanGetBodySpace(varFloorplanGetBodySpace)

	return err
}

type NullableFloorplanGetBodySpace struct {
	value *FloorplanGetBodySpace
	isSet bool
}

func (v NullableFloorplanGetBodySpace) Get() *FloorplanGetBodySpace {
	return v.value
}

func (v *NullableFloorplanGetBodySpace) Set(val *FloorplanGetBodySpace) {
	v.value = val
	v.isSet = true
}

func (v NullableFloorplanGetBodySpace) IsSet() bool {
	return v.isSet
}

func (v *NullableFloorplanGetBodySpace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFloorplanGetBodySpace(val *FloorplanGetBodySpace) *NullableFloorplanGetBodySpace {
	return &NullableFloorplanGetBodySpace{value: val, isSet: true}
}

func (v NullableFloorplanGetBodySpace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFloorplanGetBodySpace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


