/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AccountOIDCProvider type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountOIDCProvider{}

// AccountOIDCProvider struct for AccountOIDCProvider
type AccountOIDCProvider struct {
	// Client ID of the application registered with the identity provider.
	ClientId string `json:"clientId"`
	// Whether a client secret is stored. The secret itself is never returned.
	ClientSecretSet bool `json:"clientSecretSet"`
	CreatedAt time.Time `json:"createdAt"`
	OidcProviderId int64 `json:"oidcProviderId"`
	// Identity provider product the account signs in through.
	ProviderName string `json:"providerName"`
	// Organisation at the identity provider: a Microsoft Entra tenant ID or verified domain, or the PingFederate domain.
	Tenant string `json:"tenant"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type _AccountOIDCProvider AccountOIDCProvider

// NewAccountOIDCProvider instantiates a new AccountOIDCProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountOIDCProvider(clientId string, clientSecretSet bool, createdAt time.Time, oidcProviderId int64, providerName string, tenant string, updatedAt time.Time) *AccountOIDCProvider {
	this := AccountOIDCProvider{}
	this.ClientId = clientId
	this.ClientSecretSet = clientSecretSet
	this.CreatedAt = createdAt
	this.OidcProviderId = oidcProviderId
	this.ProviderName = providerName
	this.Tenant = tenant
	this.UpdatedAt = updatedAt
	return &this
}

// NewAccountOIDCProviderWithDefaults instantiates a new AccountOIDCProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountOIDCProviderWithDefaults() *AccountOIDCProvider {
	this := AccountOIDCProvider{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *AccountOIDCProvider) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *AccountOIDCProvider) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *AccountOIDCProvider) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecretSet returns the ClientSecretSet field value
func (o *AccountOIDCProvider) GetClientSecretSet() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ClientSecretSet
}

// GetClientSecretSetOk returns a tuple with the ClientSecretSet field value
// and a boolean to check if the value has been set.
func (o *AccountOIDCProvider) GetClientSecretSetOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecretSet, true
}

// SetClientSecretSet sets field value
func (o *AccountOIDCProvider) SetClientSecretSet(v bool) {
	o.ClientSecretSet = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AccountOIDCProvider) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AccountOIDCProvider) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AccountOIDCProvider) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetOidcProviderId returns the OidcProviderId field value
func (o *AccountOIDCProvider) GetOidcProviderId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OidcProviderId
}

// GetOidcProviderIdOk returns a tuple with the OidcProviderId field value
// and a boolean to check if the value has been set.
func (o *AccountOIDCProvider) GetOidcProviderIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OidcProviderId, true
}

// SetOidcProviderId sets field value
func (o *AccountOIDCProvider) SetOidcProviderId(v int64) {
	o.OidcProviderId = v
}

// GetProviderName returns the ProviderName field value
func (o *AccountOIDCProvider) GetProviderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderName
}

// GetProviderNameOk returns a tuple with the ProviderName field value
// and a boolean to check if the value has been set.
func (o *AccountOIDCProvider) GetProviderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderName, true
}

// SetProviderName sets field value
func (o *AccountOIDCProvider) SetProviderName(v string) {
	o.ProviderName = v
}

// GetTenant returns the Tenant field value
func (o *AccountOIDCProvider) GetTenant() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value
// and a boolean to check if the value has been set.
func (o *AccountOIDCProvider) GetTenantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tenant, true
}

// SetTenant sets field value
func (o *AccountOIDCProvider) SetTenant(v string) {
	o.Tenant = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AccountOIDCProvider) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AccountOIDCProvider) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AccountOIDCProvider) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o AccountOIDCProvider) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountOIDCProvider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["clientId"] = o.ClientId
	toSerialize["clientSecretSet"] = o.ClientSecretSet
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["oidcProviderId"] = o.OidcProviderId
	toSerialize["providerName"] = o.ProviderName
	toSerialize["tenant"] = o.Tenant
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *AccountOIDCProvider) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"clientId",
		"clientSecretSet",
		"createdAt",
		"oidcProviderId",
		"providerName",
		"tenant",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccountOIDCProvider := _AccountOIDCProvider{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAccountOIDCProvider)

	if err != nil {
		return err
	}

	*o = AccountOIDCProvider(varAccountOIDCProvider)

	return err
}

type NullableAccountOIDCProvider struct {
	value *AccountOIDCProvider
	isSet bool
}

func (v NullableAccountOIDCProvider) Get() *AccountOIDCProvider {
	return v.value
}

func (v *NullableAccountOIDCProvider) Set(val *AccountOIDCProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountOIDCProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountOIDCProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountOIDCProvider(val *AccountOIDCProvider) *NullableAccountOIDCProvider {
	return &NullableAccountOIDCProvider{value: val, isSet: true}
}

func (v NullableAccountOIDCProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountOIDCProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


