/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
)

// checks if the DashboardUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardUpdate{}

// DashboardUpdate struct for DashboardUpdate
type DashboardUpdate struct {
	Description *string `json:"description,omitempty"`
	Move *int32 `json:"move,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewDashboardUpdate instantiates a new DashboardUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardUpdate() *DashboardUpdate {
	this := DashboardUpdate{}
	return &this
}

// NewDashboardUpdateWithDefaults instantiates a new DashboardUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardUpdateWithDefaults() *DashboardUpdate {
	this := DashboardUpdate{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DashboardUpdate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DashboardUpdate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DashboardUpdate) SetDescription(v string) {
	o.Description = &v
}

// GetMove returns the Move field value if set, zero value otherwise.
func (o *DashboardUpdate) GetMove() int32 {
	if o == nil || IsNil(o.Move) {
		var ret int32
		return ret
	}
	return *o.Move
}

// GetMoveOk returns a tuple with the Move field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardUpdate) GetMoveOk() (*int32, bool) {
	if o == nil || IsNil(o.Move) {
		return nil, false
	}
	return o.Move, true
}

// HasMove returns a boolean if a field has been set.
func (o *DashboardUpdate) HasMove() bool {
	if o != nil && !IsNil(o.Move) {
		return true
	}

	return false
}

// SetMove gets a reference to the given int32 and assigns it to the Move field.
func (o *DashboardUpdate) SetMove(v int32) {
	o.Move = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DashboardUpdate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardUpdate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DashboardUpdate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DashboardUpdate) SetName(v string) {
	o.Name = &v
}

func (o DashboardUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Move) {
		toSerialize["move"] = o.Move
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableDashboardUpdate struct {
	value *DashboardUpdate
	isSet bool
}

func (v NullableDashboardUpdate) Get() *DashboardUpdate {
	return v.value
}

func (v *NullableDashboardUpdate) Set(val *DashboardUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardUpdate(val *DashboardUpdate) *NullableDashboardUpdate {
	return &NullableDashboardUpdate{value: val, isSet: true}
}

func (v NullableDashboardUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


