/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthRefreshTokenResBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthRefreshTokenResBody{}

// AuthRefreshTokenResBody struct for AuthRefreshTokenResBody
type AuthRefreshTokenResBody struct {
	AccessToken string `json:"accessToken"`
}

type _AuthRefreshTokenResBody AuthRefreshTokenResBody

// NewAuthRefreshTokenResBody instantiates a new AuthRefreshTokenResBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthRefreshTokenResBody(accessToken string) *AuthRefreshTokenResBody {
	this := AuthRefreshTokenResBody{}
	this.AccessToken = accessToken
	return &this
}

// NewAuthRefreshTokenResBodyWithDefaults instantiates a new AuthRefreshTokenResBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthRefreshTokenResBodyWithDefaults() *AuthRefreshTokenResBody {
	this := AuthRefreshTokenResBody{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *AuthRefreshTokenResBody) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *AuthRefreshTokenResBody) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *AuthRefreshTokenResBody) SetAccessToken(v string) {
	o.AccessToken = v
}

func (o AuthRefreshTokenResBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthRefreshTokenResBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accessToken"] = o.AccessToken
	return toSerialize, nil
}

func (o *AuthRefreshTokenResBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accessToken",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthRefreshTokenResBody := _AuthRefreshTokenResBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthRefreshTokenResBody)

	if err != nil {
		return err
	}

	*o = AuthRefreshTokenResBody(varAuthRefreshTokenResBody)

	return err
}

type NullableAuthRefreshTokenResBody struct {
	value *AuthRefreshTokenResBody
	isSet bool
}

func (v NullableAuthRefreshTokenResBody) Get() *AuthRefreshTokenResBody {
	return v.value
}

func (v *NullableAuthRefreshTokenResBody) Set(val *AuthRefreshTokenResBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthRefreshTokenResBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthRefreshTokenResBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthRefreshTokenResBody(val *AuthRefreshTokenResBody) *NullableAuthRefreshTokenResBody {
	return &NullableAuthRefreshTokenResBody{value: val, isSet: true}
}

func (v NullableAuthRefreshTokenResBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthRefreshTokenResBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


