/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChangelogValueOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangelogValueOption{}

// ChangelogValueOption struct for ChangelogValueOption
type ChangelogValueOption struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Value float64 `json:"value"`
}

type _ChangelogValueOption ChangelogValueOption

// NewChangelogValueOption instantiates a new ChangelogValueOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangelogValueOption(id string, name string, value float64) *ChangelogValueOption {
	this := ChangelogValueOption{}
	this.Id = id
	this.Name = name
	this.Value = value
	return &this
}

// NewChangelogValueOptionWithDefaults instantiates a new ChangelogValueOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangelogValueOptionWithDefaults() *ChangelogValueOption {
	this := ChangelogValueOption{}
	return &this
}

// GetId returns the Id field value
func (o *ChangelogValueOption) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChangelogValueOption) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChangelogValueOption) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ChangelogValueOption) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ChangelogValueOption) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ChangelogValueOption) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *ChangelogValueOption) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ChangelogValueOption) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ChangelogValueOption) SetValue(v float64) {
	o.Value = v
}

func (o ChangelogValueOption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangelogValueOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *ChangelogValueOption) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangelogValueOption := _ChangelogValueOption{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChangelogValueOption)

	if err != nil {
		return err
	}

	*o = ChangelogValueOption(varChangelogValueOption)

	return err
}

type NullableChangelogValueOption struct {
	value *ChangelogValueOption
	isSet bool
}

func (v NullableChangelogValueOption) Get() *ChangelogValueOption {
	return v.value
}

func (v *NullableChangelogValueOption) Set(val *ChangelogValueOption) {
	v.value = val
	v.isSet = true
}

func (v NullableChangelogValueOption) IsSet() bool {
	return v.isSet
}

func (v *NullableChangelogValueOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangelogValueOption(val *ChangelogValueOption) *NullableChangelogValueOption {
	return &NullableChangelogValueOption{value: val, isSet: true}
}

func (v NullableChangelogValueOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangelogValueOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


