/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FloorplanCreateSpaceRepeated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FloorplanCreateSpaceRepeated{}

// FloorplanCreateSpaceRepeated struct for FloorplanCreateSpaceRepeated
type FloorplanCreateSpaceRepeated struct {
	Spaces []FloorplanCreateSpace `json:"spaces"`
}

type _FloorplanCreateSpaceRepeated FloorplanCreateSpaceRepeated

// NewFloorplanCreateSpaceRepeated instantiates a new FloorplanCreateSpaceRepeated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFloorplanCreateSpaceRepeated(spaces []FloorplanCreateSpace) *FloorplanCreateSpaceRepeated {
	this := FloorplanCreateSpaceRepeated{}
	this.Spaces = spaces
	return &this
}

// NewFloorplanCreateSpaceRepeatedWithDefaults instantiates a new FloorplanCreateSpaceRepeated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFloorplanCreateSpaceRepeatedWithDefaults() *FloorplanCreateSpaceRepeated {
	this := FloorplanCreateSpaceRepeated{}
	return &this
}

// GetSpaces returns the Spaces field value
func (o *FloorplanCreateSpaceRepeated) GetSpaces() []FloorplanCreateSpace {
	if o == nil {
		var ret []FloorplanCreateSpace
		return ret
	}

	return o.Spaces
}

// GetSpacesOk returns a tuple with the Spaces field value
// and a boolean to check if the value has been set.
func (o *FloorplanCreateSpaceRepeated) GetSpacesOk() ([]FloorplanCreateSpace, bool) {
	if o == nil {
		return nil, false
	}
	return o.Spaces, true
}

// SetSpaces sets field value
func (o *FloorplanCreateSpaceRepeated) SetSpaces(v []FloorplanCreateSpace) {
	o.Spaces = v
}

func (o FloorplanCreateSpaceRepeated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FloorplanCreateSpaceRepeated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["spaces"] = o.Spaces
	return toSerialize, nil
}

func (o *FloorplanCreateSpaceRepeated) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spaces",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFloorplanCreateSpaceRepeated := _FloorplanCreateSpaceRepeated{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFloorplanCreateSpaceRepeated)

	if err != nil {
		return err
	}

	*o = FloorplanCreateSpaceRepeated(varFloorplanCreateSpaceRepeated)

	return err
}

type NullableFloorplanCreateSpaceRepeated struct {
	value *FloorplanCreateSpaceRepeated
	isSet bool
}

func (v NullableFloorplanCreateSpaceRepeated) Get() *FloorplanCreateSpaceRepeated {
	return v.value
}

func (v *NullableFloorplanCreateSpaceRepeated) Set(val *FloorplanCreateSpaceRepeated) {
	v.value = val
	v.isSet = true
}

func (v NullableFloorplanCreateSpaceRepeated) IsSet() bool {
	return v.isSet
}

func (v *NullableFloorplanCreateSpaceRepeated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFloorplanCreateSpaceRepeated(val *FloorplanCreateSpaceRepeated) *NullableFloorplanCreateSpaceRepeated {
	return &NullableFloorplanCreateSpaceRepeated{value: val, isSet: true}
}

func (v NullableFloorplanCreateSpaceRepeated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFloorplanCreateSpaceRepeated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


