/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MissingObjectDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MissingObjectDetail{}

// MissingObjectDetail struct for MissingObjectDetail
type MissingObjectDetail struct {
	Object string `json:"object"`
}

type _MissingObjectDetail MissingObjectDetail

// NewMissingObjectDetail instantiates a new MissingObjectDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMissingObjectDetail(object string) *MissingObjectDetail {
	this := MissingObjectDetail{}
	this.Object = object
	return &this
}

// NewMissingObjectDetailWithDefaults instantiates a new MissingObjectDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMissingObjectDetailWithDefaults() *MissingObjectDetail {
	this := MissingObjectDetail{}
	return &this
}

// GetObject returns the Object field value
func (o *MissingObjectDetail) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *MissingObjectDetail) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *MissingObjectDetail) SetObject(v string) {
	o.Object = v
}

func (o MissingObjectDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MissingObjectDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	return toSerialize, nil
}

func (o *MissingObjectDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMissingObjectDetail := _MissingObjectDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMissingObjectDetail)

	if err != nil {
		return err
	}

	*o = MissingObjectDetail(varMissingObjectDetail)

	return err
}

type NullableMissingObjectDetail struct {
	value *MissingObjectDetail
	isSet bool
}

func (v NullableMissingObjectDetail) Get() *MissingObjectDetail {
	return v.value
}

func (v *NullableMissingObjectDetail) Set(val *MissingObjectDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableMissingObjectDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableMissingObjectDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMissingObjectDetail(val *MissingObjectDetail) *NullableMissingObjectDetail {
	return &NullableMissingObjectDetail{value: val, isSet: true}
}

func (v NullableMissingObjectDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMissingObjectDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


