/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TopDownModelEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TopDownModelEntry{}

// TopDownModelEntry struct for TopDownModelEntry
type TopDownModelEntry struct {
	Description string `json:"description"`
	Id string `json:"id"`
	Name string `json:"name"`
}

type _TopDownModelEntry TopDownModelEntry

// NewTopDownModelEntry instantiates a new TopDownModelEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopDownModelEntry(description string, id string, name string) *TopDownModelEntry {
	this := TopDownModelEntry{}
	this.Description = description
	this.Id = id
	this.Name = name
	return &this
}

// NewTopDownModelEntryWithDefaults instantiates a new TopDownModelEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopDownModelEntryWithDefaults() *TopDownModelEntry {
	this := TopDownModelEntry{}
	return &this
}

// GetDescription returns the Description field value
func (o *TopDownModelEntry) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TopDownModelEntry) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TopDownModelEntry) SetDescription(v string) {
	o.Description = v
}

// GetId returns the Id field value
func (o *TopDownModelEntry) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TopDownModelEntry) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TopDownModelEntry) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TopDownModelEntry) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TopDownModelEntry) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TopDownModelEntry) SetName(v string) {
	o.Name = v
}

func (o TopDownModelEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopDownModelEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *TopDownModelEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTopDownModelEntry := _TopDownModelEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTopDownModelEntry)

	if err != nil {
		return err
	}

	*o = TopDownModelEntry(varTopDownModelEntry)

	return err
}

type NullableTopDownModelEntry struct {
	value *TopDownModelEntry
	isSet bool
}

func (v NullableTopDownModelEntry) Get() *TopDownModelEntry {
	return v.value
}

func (v *NullableTopDownModelEntry) Set(val *TopDownModelEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableTopDownModelEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableTopDownModelEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopDownModelEntry(val *TopDownModelEntry) *NullableTopDownModelEntry {
	return &NullableTopDownModelEntry{value: val, isSet: true}
}

func (v NullableTopDownModelEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopDownModelEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


