/*
spaciv API

The spaciv API powers workplace planning: modelling how many people an organisation has, how they work, and how much space that requires.  ## Getting started  1. Exchange credentials for an access token using one of the operations under    **Authentication**. 2. Send that token on every subsequent request as `Authorization: Bearer <token>`. 3. Access tokens are short lived. Call `POST /v1/auth/refresh-token` to obtain a new one    before the old one expires.  ## Conventions  Every operation is versioned under `/v1`. Collections are plural (`GET /v1/dashboards` lists, `POST /v1/dashboards` creates) and individual records live beneath them (`/v1/dashboards/{id}`). Singular paths such as `/v1/account`, `/v1/project` and `/v1/user` refer to the record the access token was issued for.  Request and response bodies are JSON. Timestamps are RFC 3339. Identifiers are opaque strings unless documented otherwise, and collection operations return the records visible to the account the token was issued for.  Failures return an [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) problem document with a `detail` field describing what went wrong.

API version: 1.0.0
Contact: support@spaciv.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package spaciv

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ObjectGroupEntryChangelogBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectGroupEntryChangelogBody{}

// ObjectGroupEntryChangelogBody struct for ObjectGroupEntryChangelogBody
type ObjectGroupEntryChangelogBody struct {
	Name string `json:"name"`
	Properties map[string]ObjectGroupEntryPropertyNodes `json:"properties"`
	User string `json:"user"`
}

type _ObjectGroupEntryChangelogBody ObjectGroupEntryChangelogBody

// NewObjectGroupEntryChangelogBody instantiates a new ObjectGroupEntryChangelogBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectGroupEntryChangelogBody(name string, properties map[string]ObjectGroupEntryPropertyNodes, user string) *ObjectGroupEntryChangelogBody {
	this := ObjectGroupEntryChangelogBody{}
	this.Name = name
	this.Properties = properties
	this.User = user
	return &this
}

// NewObjectGroupEntryChangelogBodyWithDefaults instantiates a new ObjectGroupEntryChangelogBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectGroupEntryChangelogBodyWithDefaults() *ObjectGroupEntryChangelogBody {
	this := ObjectGroupEntryChangelogBody{}
	return &this
}

// GetName returns the Name field value
func (o *ObjectGroupEntryChangelogBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ObjectGroupEntryChangelogBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ObjectGroupEntryChangelogBody) SetName(v string) {
	o.Name = v
}

// GetProperties returns the Properties field value
func (o *ObjectGroupEntryChangelogBody) GetProperties() map[string]ObjectGroupEntryPropertyNodes {
	if o == nil {
		var ret map[string]ObjectGroupEntryPropertyNodes
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *ObjectGroupEntryChangelogBody) GetPropertiesOk() (map[string]ObjectGroupEntryPropertyNodes, bool) {
	if o == nil {
		return map[string]ObjectGroupEntryPropertyNodes{}, false
	}
	return o.Properties, true
}

// SetProperties sets field value
func (o *ObjectGroupEntryChangelogBody) SetProperties(v map[string]ObjectGroupEntryPropertyNodes) {
	o.Properties = v
}

// GetUser returns the User field value
func (o *ObjectGroupEntryChangelogBody) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *ObjectGroupEntryChangelogBody) GetUserOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *ObjectGroupEntryChangelogBody) SetUser(v string) {
	o.User = v
}

func (o ObjectGroupEntryChangelogBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectGroupEntryChangelogBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["properties"] = o.Properties
	toSerialize["user"] = o.User
	return toSerialize, nil
}

func (o *ObjectGroupEntryChangelogBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"properties",
		"user",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectGroupEntryChangelogBody := _ObjectGroupEntryChangelogBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varObjectGroupEntryChangelogBody)

	if err != nil {
		return err
	}

	*o = ObjectGroupEntryChangelogBody(varObjectGroupEntryChangelogBody)

	return err
}

type NullableObjectGroupEntryChangelogBody struct {
	value *ObjectGroupEntryChangelogBody
	isSet bool
}

func (v NullableObjectGroupEntryChangelogBody) Get() *ObjectGroupEntryChangelogBody {
	return v.value
}

func (v *NullableObjectGroupEntryChangelogBody) Set(val *ObjectGroupEntryChangelogBody) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectGroupEntryChangelogBody) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectGroupEntryChangelogBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectGroupEntryChangelogBody(val *ObjectGroupEntryChangelogBody) *NullableObjectGroupEntryChangelogBody {
	return &NullableObjectGroupEntryChangelogBody{value: val, isSet: true}
}

func (v NullableObjectGroupEntryChangelogBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectGroupEntryChangelogBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


